### PR TITLE
Fix help message flags on docker stack commands and sub-commands

### LINKED ISSUE #1243: docker stack deploy help is missing orchestration specific flags
**Description**

The help message for `docker stack deploy --help` does not include orchestrator specific options.

**Steps to reproduce the issue:**

Run any of:

- `docker stack deploy --help`
- `docker stack deploy --orchestrator swarm --help`
- `docker stack --orchestrator swarm deploy --help`

**Describe the results you received:**

The output only includes the common options:

```
$ docker stack deploy --help

Usage:  docker stack deploy [OPTIONS] STACK

Deploy a new stack or update an existing stack

Aliases:
  deploy, up

Options:
  -c, --compose-file strings   Path to a Compose file
      --orchestrator string    Orchestrator to use (swarm|kubernetes|all)
```

**Describe the results you expected:**

The output should include all options, or at least the swarm specific options when run with that orchestrator flag, e.g. here's the output from a prior version (note the `--prune`, `--resolve-image` and `--with-registry-auth` options):

```
$ docker stack deploy --help

Usage:  docker stack deploy [OPTIONS] STACK

Deploy a new stack or update an existing stack

Aliases:
  deploy, up

Options:
      --bundle-file string     Path to a Distributed Application Bundle file
  -c, --compose-file strings   Path to a Compose file
      --prune                  Prune services that are no longer referenced
      --resolve-image string   Query the registry to resolve image digest and supported platforms ("always"|"changed"|"never") (default "always")
      --with-registry-auth     Send registry authentication details to Swarm agents
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:33 2018
 OS/Arch:           linux/amd64
 Experimental:      true

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:38 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
$ docker info
Containers: 10
 Running: 9
 Paused: 0
 Stopped: 1
Images: 234
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: q44zx0s2lvu1fdduk800e5ini
 Is Manager: true
 ClusterID: b4qh6x548wfo2sv9pubs33hk7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 4
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.233.100
 Manager Addresses:
  192.168.233.100:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.739GiB
Name: bmitch-asusr556l
ID: 5OZQ:RKOD:MLMQ:3YC4:QOWX:SLWX:SYO2:XDJF:CG6C:43ER:4QQ4:DXOO
Docker Root Dir: /home/var-docker
Debug Mode (client): false
Debug Mode (server): false
Username: bmitch3020
Registry: https://index.docker.io/v1/
Labels:
 foo=bar
 env=laptop
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is on a native Linux install on bare metal.

### PR DESCRIPTION
**Pull request by silvin-lubecki**
**- What I did**
Fix issue #1243 
Add an e2e test as regression test

**- How I did it**
PersistentPreRunE needs to be called within the help function to initialize all the flags (notably the orchestrator flag)

**- How to verify it**
```sh
$ docker stack deploy --help --orchestrator=kubernetes

Usage:	docker stack deploy [OPTIONS] STACK

Deploy a new stack or update an existing stack

Aliases:
  deploy, up

Options:
  -c, --compose-file strings   Path to a Compose file, or "-" to read from stdin
      --kubeconfig string      Kubernetes config file
      --namespace string       Kubernetes namespace to use
      --orchestrator string    Orchestrator to use (swarm|kubernetes|all)

$ docker stack deploy --help --orchestrator=swarm

Usage:	docker stack deploy [OPTIONS] STACK

Deploy a new stack or update an existing stack

Aliases:
  deploy, up

Options:
      --bundle-file string     Path to a Distributed Application Bundle file
  -c, --compose-file strings   Path to a Compose file, or "-" to read from stdin
      --orchestrator string    Orchestrator to use (swarm|kubernetes|all)
      --prune                  Prune services that are no longer referenced
      --resolve-image string   Query the registry to resolve image digest and supported platforms ("always"|"changed"|"never") (default "always")
      --with-registry-auth     Send registry authentication details to Swarm agents
```

**- Description for the changelog**
* Fix #1243 help message flags on docker stack commands and sub-commands

**- A picture of a cute animal (not mandatory but encouraged)**
image

Lots of kudos for @albers !!

### CODE REVIEW

File: e2e/stack/help_test.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+	})
+	t.Run("Kubernetes", func(t *testing.T) {
+		testStackDeployHelp(t, "kubernetes")
+	})
+}
+
+func testStackDeployHelp(t *testing.T, orchestrator string) {
+	result := icmd.RunCommand("docker", "stack", "deploy", "--orchestrator", orchestrator, "--help")
+	result.Assert(t, icmd.Success)
+	golden.Assert(t, result.Stdout(), fmt.Sprintf("stack-deploy-help-%s.golden", orchestrator))
```
Comment (albers) [inline e2e/stack/help_test.go]: Is this the commonly used way to verify command outputs in this project? This will break every time an option or help message is added/modified, this producing unnecessary maintenance work.

Alternatively, we could check for the presence of specific flags via substring checks.

**Comment by albers** [comment]
There is also a problem in `docker version`: `--kubeconfig` is annotated as _kubernetes_ but visible for the _swarm_ orchestrator.

```bash
# DOCKER_STACK_ORCHESTRATOR=swarm docker version --help | grep kubeconfig
      --kubeconfig string   Kubernetes config file
# DOCKER_STACK_ORCHESTRATOR=kubernetes docker version --help | grep kubeconfig
      --kubeconfig string   Kubernetes config file
# docker --version
Docker version 18.09.0-dev, build 21cce52b
```

**Comment by silvin-lubecki** [comment]
@albers I'll fix the `docker version` flags in a follow-up.

**Comment by silvin-lubecki** [comment]
Well the problem is that the root docker command does a lot of stuffs with the help command (formatting included), so testing at the stack command level won't really help testing the final feature.

**Comment by albers** [comment]
> I'll fix the docker version flags in a follow-up.

@silvin-lubecki I created #1265 as a reminder.
