### PR TITLE
Fix psFormat's Size handling in config file

### LINKED ISSUE #3632: `docker ps` using `psFormat` in config that contains `Size` does not behave as expected
**Description**

I have created a config.json file in my .docker folder which specifies a `psFormat` which includes `.Size`.
When I execute `docker ps`, the SIZE column shows 0B. If I specify the same format on the command line, the size is shown as expected.

The logic for [`--format`](https://github.com/docker/cli/blob/14962747e4af2c992bca55008c27387cd2268620/cli/command/container/list.go#L81) checks for size and modifies the `Size` option if the format includes size, but if `--format` is not set, it seems that a format that doesn't contain `Size` is assumed.

**Steps to reproduce the issue:**
1. Create a config.json file with `psFormat` = `"table {{.ID}}\t{{.RunningFor}}\t{{.Status}}\t{{.Size}}"`
2. Run `docker ps`

**Describe the results you received:**
Something similar to:
```
CONTAINER ID   CREATED        STATUS        SIZE
d367e8c585df   46 hours ago   Up 46 hours   0B
1a3eeef4e88b   5 days ago     Up 5 days     0B
b9fddd45560e   5 days ago     Up 5 days     0B
efd0485c7898   7 days ago     Up 7 days     0B
6be3e03c5351   8 days ago     Up 8 days     0B
...
```

**Describe the results you expected:**
Something similar to:
```
CONTAINER ID   CREATED        STATUS        SIZE
d367e8c585df   46 hours ago   Up 46 hours   0B (virtual 313MB)
1a3eeef4e88b   5 days ago     Up 5 days     257B (virtual 401MB)
b9fddd45560e   5 days ago     Up 5 days     0B (virtual 455MB)
efd0485c7898   7 days ago     Up 7 days     8.19kB (virtual 317MB)
6be3e03c5351   8 days ago     Up 8 days     8.19kB (virtual 313MB)
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           20.10.12-ce
 API version:       1.41
 Go version:        go1.16.13
 Git commit:        459d0dfbbb51
 Built:             Mon Jan 17 12:00:00 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12-ce
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.13
  Git commit:       459d0dfbbb51
  Built:            Mon Jan 17 12:00:00 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.3
  GitCommit:
 docker-init:
  Version:          0.1.5_catatonit
  GitCommit:
```

**Output of `docker info`:**

```
Client:
 Version:           20.10.12-ce
 API version:       1.41
 Go version:        go1.16.13
 Git commit:        459d0dfbbb51
 Built:             Mon Jan 17 12:00:00 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12-ce
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.13
  Git commit:       459d0dfbbb51
  Built:            Mon Jan 17 12:00:00 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.3
  GitCommit:
 docker-init:
  Version:          0.1.5_catatonit
  GitCommit:
jon_s@LINUX-SERVER:~ > docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 19
  Running: 19
  Paused: 0
  Stopped: 0
 Images: 223
 Server Version: 20.10.12-ce
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.18-150300.59.54-default
 Operating System: openSUSE Leap 15.3
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 19.37GiB
 Name: LINUX-SERVER
 ID: RMKV:5FJ7:TQRJ:ENCG:3WK5:Y3ND:GYEQ:HJ36:4OSP:ROSX:6GB3:7FQJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OpenSuse Leap 15.3
```
docker                 | package | 20.10.12_ce-159.1 | x86_64 | Update repository with updates from SUSE Linux Enterprise 15
docker-bash-completion | package | 20.10.12_ce-159.1 | noarch | Update repository with updates from SUSE Linux Enterprise 15
zypper-docker          | package | 2.0.0-3.5.1       | x86_64 | Main Repository
```

### PR DESCRIPTION
**Pull request by photra**
**- What I did**
Fixed #3632 

**- How I did it**
1. Added check for `Size` usage in config file's `PsFormat`, and moved this logic before calling `containerList`
2. Added `WithSize` function in test builder to allow specifying container size in unit tests
3. Amended `TestContainerListWithConfigFormat` to test for changes above

**- How to verify it**
Run the full test suite via `docker buildx bake test`, then attempt to reproduce issue above

**- Description for the changelog**
Fixed incorrect size handling in config file when using docker ps

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by photra** [comment]
@thaJeztah thanks for merging my deflake PR the other day! Can you review this one as well?

File: cli/command/container/list.go [hunk 1]
```diff
@@ -114,20 +114,35 @@ func runPs(dockerCli command.Cli, options *psOptions) error {
...
-	if err != nil {
-		return err
-	}
-
 	format := options.format
 	if len(format) == 0 {
 		if len(dockerCli.ConfigFile().PsFormat) > 0 && !options.quiet {
 			format = dockerCli.ConfigFile().PsFormat
+
+			tmpl, err := templates.NewParse("", format)
```
[the remark this answers is not in the document]
Comment (thaJeztah) [reply cli/command/container/list.go:122]: I opened https://github.com/photra/cli/pull/1 in your repository; let me know if that looks good to you; if you merge that one, please squash the commits afterwards (let me know if you need help on that)

File: internal/test/builders/container.go [hunk 2]
```diff
@@ -61,6 +61,15 @@ func WithPort(privateport, publicport uint16, builders ...func(*types.Port)) fun
 	}
 }
 
+// WithSize adds size in bytes to the container
+func WithSize(size int64) func(*types.Container) {
+	return func(c *types.Container) {
+		if size >= 0 {
```
Comment (thaJeztah) [inline internal/test/builders/container.go:67]: nit; this probably is redundant (perhaps there's cases where we'd would want to _reset_ an earlier set value?)

Comment (photra) [reply internal/test/builders/container.go:67]: Hmm, that's true 🤔. I originally added this function to update `TestContainerListWithConfigFormat` for better clarity, but I do see your point on redundancy. Would you like to remove it from this PR?

Comment (thaJeztah) [reply internal/test/builders/container.go:67]: 🤦‍♂️ ☺️  Oh, actually, erm....
Ignore my comment;  I must've read `if size > 0` 😅☺️

It's fine as it is 👌👍

**Comment by photra** [comment]
@thaJeztah looks like we're all set to merge! Thank you for working on this with me 😄 I learned a lot in the process!

**Comment by thaJeztah** [comment]
Awesome! Changes look good 😅 - let me do a quick rebase and squash

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!!
