### PR TITLE
Fix service filtering by name on Kubernetes

### LINKED ISSUE #1092: Filtering on stack service name with Kubernetes should match prefix
**Description**
When we filter on a service name, it requires an exact match, but it should follow swarm filter and match the prefix:
``` sh
# Kubernetes matches only exact name
$ docker stack service mystack --filter name=exact-name --orchestrator=kubernetes
ID                  NAME                   MODE                REPLICAS            IMAGE                 PORTS
af5e0438-634        mystack_exact-name     replicated          0/1                 docker-teaches-code   *:8080->8080/tcp

# And not prefix
$ docker stack service mystack --filter name=exact --orchestrator=kubernetes
ID                  NAME                   MODE                REPLICAS            IMAGE                 PORTS

# But swarm does
$ docker stack service mystack --filter name=exact --orchestrator=swarm
ID                  NAME                   MODE                REPLICAS            IMAGE                 PORTS
n6arf4cjh6av        mystack_exact-name     replicated          0/1                 docker-teaches-code   *:8080->8080/tcp
```

### PR DESCRIPTION
**Pull request by silvin-lubecki**
**- What I did**
Fix #1092 by filtering services by name but client side.

**- How to verify it**
```
# Deploy a stack with multiple services
$ docker stack deploy mystack -c docker-compose.yml --orchestrator=kubernetes

# Docker service matches exact name
$ docker stack service mystack --filter name=my-service --orchestrator=kubernetes
ID                  NAME                   MODE                REPLICAS            IMAGE                 PORTS
af5e0438-634        mystack_my-service     replicated          0/1                 docker-teaches-code   *:8080->8080/tcp

# But also prefix
$ docker stack service mystack --filter name=my-se --orchestrator=kubernetes
ID                  NAME                   MODE                REPLICAS            IMAGE                 PORTS
af5e0438-634        mystack_my-service     replicated          0/1                 docker-teaches-code   *:8080->8080/tcp
```

**- Description for the changelog**
Fix #1092 filtering stack service name by prefix

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

File: cli/command/stack/kubernetes/services.go [hunk 1]
```diff
@@ -140,3 +133,27 @@ func RunServices(dockerCli *KubeCli, opts options.Services) error {
 	}
 	return formatter.ServiceListWrite(servicesCtx, services, info)
 }
+
+func filterServicesByName(services []swarm.Service, f filters.Args, stackName string) []swarm.Service {
+	names := f.Get("name")
```
Comment (thaJeztah) [inline cli/command/stack/kubernetes/services.go]: Would it be clearer to pass `names []string` as argument instead of the filter-set?

**Comment by silvin-lubecki** [comment]
PTAL
