### PR TITLE
Handle case of configs on old daemon

### LINKED ISSUE #150: Stack deploy fails with 17.06.0-rc1 client against 17.05.0 swarm
**Description**

I'm having some difficultly deploying a simple stack to a swarm running Docker 17.05.0 from a 17.06.0-rc1 client. I get `Error response from daemon: page not found`.

**Steps to reproduce the issue:**

Given the following Compose file:

```
version: '3.2'

services:
  mssql:
    image: microsoft/mssql-server-linux:ctp2-1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=converis
    networks:
      - data

networks:
  data:
```

1. Set DOCKER_HOST to point to a Docker 17.05.0 swarm controller.
2. Run `docker stack deploy -c stack.yml dm`.

**Describe the results you received:**

The deploy fails with the following output.

```
(swarm) →  dm git:(review-stack) ✗ docker -D stack deploy -c stack.yml dm
DEBU[0000] Trusting 1 certs                             
DEBU[0000] Trusting 1 certs                             
Creating network dm_data
service mssql: Error response from daemon: page not found
```

**Describe the results you expected:**

The `data` network and `mssql` service should be created.

**Additional information you deem important (e.g. issue happens only occasionally):**

Using the same Docker 17.06.0-rc1 client against a Docker 17.06.0-rc1 swarm works fine. As does using a Docker 17.05.0 client against the Docker 17.05.0 swarm. I only get the error going from the 17.06.0-rc1 client to the 17.05.0 swarm.

**Output of `docker version`:**

```
(swarm) →  dm git:(review-stack) ✗ docker version
Client:
 Version:      17.06.0-ce-rc1
 API version:  1.29 (downgraded from 1.30)
 Go version:   go1.8.1
 Git commit:   7f8486a
 Built:        Wed May 31 02:56:01 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
(swarm) →  dm git:(review-stack) ✗ docker info
Containers: 23
 Running: 20
 Paused: 0
 Stopped: 3
Images: 50
Server Version: 17.05.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 55.15GB
 Data Space Total: 65.28GB
 Data Space Available: 10.12GB
 Metadata Space Used: 17.87MB
 Metadata Space Total: 683.7MB
 Metadata Space Available: 665.8MB
 Thin Pool Minimum Free Space: 6.527GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: 
Swarm: active
 NodeID: svhio5na7zjds72nnw55gjrwh
 Is Manager: true
 ClusterID: 1dbs7dgdqmz5u8h2bncrzmh88
 Managers: 4
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 10.43.64.10
 Manager Addresses:
  10.43.64.10:2377
  10.43.64.11:2377
  10.43.64.12:2377
  10.43.64.13:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51GiB
Name: itpocnode01.ucalgary.ca
ID: OM7K:NNN7:75VJ:I34C:W5ZS:TCYH:ZGPH:SRXP:HINS:7O2W:IZQ4:QIGD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Client is using Docker for Mac (edge). 17.05.0 swarm is 4 RHEL 7.3 VMs. 17.06.0-rc1 is Docker for Mac (edge) in swarm mode.

### PR DESCRIPTION
**Pull request by vdemeester**
If configs are declared for a service and pointing on an old
daemon, error out properly (instead of "page not found").

If there is no configs declared, don't call convertServiceConfigObjs
to avoid having an error.

Fix #150 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

File: cli/compose/convert/service.go [hunk 1]
```diff
@@ -36,9 +37,19 @@ func Services(
 		if err != nil {
 			return nil, errors.Wrapf(err, "service %s", service.Name)
 		}
-		configs, err := convertServiceConfigObjs(client, namespace, service.Configs, config.Configs)
-		if err != nil {
-			return nil, errors.Wrapf(err, "service %s", service.Name)
+		var configs []*swarm.ConfigReference
+		if len(service.Configs) > 0 {
```
Comment (thaJeztah) [inline cli/compose/convert/service.go]: What if we tied docker-compose file-version to API version? (also dirty perhaps); i.e. when attempting to use docker-compose file format 1.3.x, produce an error if the supported API version is older then Y.

Comment (thaJeztah) [inline cli/compose/convert/service.go]: Not sure if that's better, should think a bit about it 😓

Comment (vdemeester) [inline cli/compose/convert/service.go]: I'm not a huge fan of that though…

File: cli/compose/convert/service.go [hunk 2]
```diff
@@ -36,9 +37,19 @@ func Services(
...
+			version, err := client.ServerVersion(context.Background())
+			if err != nil {
+				return nil, errors.Wrapf(err, "service %s", service.Name)
+			}
+			if versions.LessThan(version.APIVersion, "1.30") {
+				return nil, errors.Errorf("Server API version (%s) doesn't support configs declared in service %s", version.APIVersion, service.Name)
```
Comment (thaJeztah) [inline cli/compose/convert/service.go]: Can you make this error consistent with the [other errors we have](https://github.com/docker/cli/blob/ed5762cb9f41f373696d7e8fbbfdf4c7af03a621/cmd/docker/docker.go#L259-L269)? 

```
docker service ls requires API version 1.24, but the Docker daemon API version is 1.10
```

File: cli/compose/convert/service.go (hunk 1 above)
Comment (dnephin) [inline cli/compose/convert/service.go]: I think that method is a lot more reliable. 

I don't understand why this would be a special case. We added secrets before and didn't have this problem.

We should just error if API version is less than the minimum version required for the Compose file version.

Comment (vdemeester) [inline cli/compose/convert/service.go]: @dnephin secrets support were already there in swarm mode when we added them in compose v3. If we point to a 1.12 daemon (that may not have secret ?), the bug will be there for secret too yep.

Comment (thaJeztah) [inline cli/compose/convert/service.go]: Oh, sorry, didn't see your comment.

I also was just looking how we handle other API endpoints that are not supported yet, and it looks like we have code to handle that, e.g.; https://github.com/moby/moby/blob/745795ef2e0089c5001e5a2fc7ba8c1ab0234857/client/container_prune.go#L16-L18

But looks like we didn't add such handling to the secrets and config API

**Comment by vdemeester** [comment]
Updated according to @dnephin comment 👼
