### PR TITLE
try http for docker manifest --insecure

### LINKED ISSUE #1631: Docker manifest push ignoring --insecure
**Description**

When attempting to push a manifest to an insecure registry, the command fails, indicating an issue with the registry server giving an HTTP response to a HTTPS client. The documentation states that passing the `--insecure` flag into the push command should fix this, but it does nothing.

**Steps to reproduce the issue:**
1. Create a manifest via `docker manifest create --insecure 192.168.0.20:5000/my-img:latest 192.168.0.20:5000/my-img-arm:latest 192.168.0.20:5000/my-img-x86:latest`
2. Annotate the manifest via `docker manifest annotate 192.168.0.20:5000/my-img:latest 192.168.0.20:5000/my-img-arm:latest --arch arm`
3. Attempt to push manifest via `docker -D manifest push --insecure 192.168.0.20:5000/my-img:latest`

**Describe the results you received:**

```
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
failed to configure transport: error pinging v2 registry: Get https://192.168.0.20:5000/v2/: http: server gave HTTP response to HTTPS client
```
This is the same exact result as when running without `--insecure`.

**Describe the results you expected:**

The manifest push succeeds.

**Additional information you deem important (e.g. issue happens only occasionally):**

I was having issues with `manifest create` as well until I updated my docker from 18.0.6 to 18.0.9. Docker pull/push with this insecure registry works fine.

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 64
 Running: 24
 Paused: 0
 Stopped: 40
Images: 1149
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.33GiB
Name: my-server
ID: DVZR:G3ZK:DAL5:BUHT:IG3J:LL5R:ITDH:UMCI:WM3Y:KI3X:ERXF:XTKQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 192.168.0.20:5000
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The registry is hosted on the same server that I am attempting to push the manifest from. The registry was version 2.6.2 (didn't work), so I updated to 2.7.1 and the bug remains.
Registry hash:
```
$ docker container inspect registry | jq .[0].Image
"sha256:116995fd662403e7ac3fd9dd698f95a7f9c8c3c321aa34cb7090a8721d68573a"
```

### PR DESCRIPTION
**Pull request by davidwtf**
**- What I did**
fixes #1631

**- How I did it**
Add retry for http when https not work

**- How to verify it**
`docker manifest push  --insecure 127.0.0.1:5000/test:v1`

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: cli/registry/client/client.go [hunk 1]
```diff
@@ -141,7 +141,22 @@ func (c *client) getRepositoryForReference(ctx context.Context, ref reference.Na
...
+						}
+					}
+				}
+
+			} else {
+				return nil, ErrHTTPProto{OrigErr: err.Error()}
+			}
 		}
 	}
 	repoName, err := reference.WithName(repoEndpoint.Name())
```
Comment (thaJeztah) [inline cli/registry/client/client.go]: Looks like this check could be done even before we connect to the registry

File: cli/registry/client/client.go [hunk 2]
```diff
@@ -141,7 +141,22 @@ func (c *client) getRepositoryForReference(ctx context.Context, ref reference.Na
 	httpTransport, err := c.getHTTPTransportForRepoEndpoint(ctx, repoEndpoint)
 	if err != nil {
 		if strings.Contains(err.Error(), "server gave HTTP response to HTTPS client") {
```
Comment (thaJeztah) [inline cli/registry/client/client.go]: Looks like there's a small bug here, and we ignore any other error?

File: cli/registry/client/client.go [hunk 3]
```diff
@@ -141,7 +141,22 @@ func (c *client) getRepositoryForReference(ctx context.Context, ref reference.Na
...
-			return nil, ErrHTTPProto{OrigErr: err.Error()}
+			if repoEndpoint.endpoint.TLSConfig.InsecureSkipVerify {
```
Comment (thaJeztah) [inline cli/registry/client/client.go]: Perhaps reverse the logic, and do an early return; with my other suggestions;

```go
func (c *client) getRepositoryForReference(ctx context.Context, ref reference.Named, repoEndpoint repositoryEndpoint) (distribution.Repository, error) {
	repoName, err := reference.WithName(repoEndpoint.Name())
	if err != nil {
		return nil, errors.Wrapf(err, "failed to parse repo name from %s", ref)
	}
	httpTransport, err := c.getHTTPTransportForRepoEndpoint(ctx, repoEndpoint)
	if err != nil {
		if !strings.Contains(err.Error(), "server gave HTTP response to HTTPS client") {
			return nil, err
		}
		if !repoEndpoint.endpoint.TLSConfig.InsecureSkipVerify {
			return nil, ErrHTTPProto{OrigErr: err.Error()}
		}
		// --insecure was set; fall back to plain HTTP
		if url := repoEndpoint.endpoint.URL; url != nil && url.Scheme == "https" {
			url.Scheme = "http"
			httpTransport, err = c.getHTTPTransportForRepoEndpoint(ctx, repoEndpoint)
			if err != nil {
				return nil, err
			}
		}
	}
	return distributionclient.NewRepository(repoName, repoEndpoint.BaseURL(), httpTransport)
}
```

Comment (davidwtf) [reply cli/registry/client/client.go]: Modified according to  your suggestion.
Thanks.

**Comment by davidwtf** [comment]
Hi @thaJeztah,
please check again. I've squashed the commits.
Thanks.

**Comment by thaJeztah** [comment]
@silvin-lubecki PTAL

**Comment by altishchenko** [comment]
Guys! Merge this Please!
