### PR TITLE
[pretty print] pretty print and healthcheck

### LINKED ISSUE #117: --health-start-period value isn't shown when pretty inspecting service
**Description**

When I set the `--health-start-period` in a service, I cannot see the set value using `docker service inspect --pretty`, 

**Steps to reproduce the issue:**
1. `docker service update foo --health-start-period 2m`
2. `docker service inspect --pretty foo | grep -i health`

**Describe the results you received:**

No results while looking for an "Health Start Period value"

**Describe the results you expected:**

I think this is an important value that should appear in the prettified output too by default. I'm aware that the whole JSON inspect output carries indeed this info under
```
                "ContainerSpec": {
                    "Healthcheck": {
                        "StartPeriod": 120000000000
                    },
```

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### PR DESCRIPTION
**Pull request by sjeandeaux**
fixes #117

Print healthcheck information in pretty mode.

Signed-off-by: Stephane Jeandeaux <stephane.jeandeaux@gmail.com>

**- What I did**
The pretty print prints the healthcheck information.

**- How I did it**
The pretty template is modified.

**- How to verify it**
The unit test is modified to test if healthcheck is there.

**- Description for the changelog**

### CODE REVIEW

File: cli/command/service/inspect_test.go [hunk 1]
```diff
@@ -7,6 +7,8 @@ import (
 	"testing"
 	"time"
 
+	"github.com/docker/docker/api/types/container"
+
```
Comment (thaJeztah) [inline cli/command/service/inspect_test.go]: nit: could you remove this blank line, and sort the imports in this group?

Comment (sjeandeaux) [reply cli/command/service/inspect_test.go]: It is done. I removed the blank line and sorted the imports.
