### PR TITLE
Sort plugin names in a natural order

### LINKED ISSUE #1164: docker plugin ls command output is not sorted by plugin name
**Description**
The output from docker plugin ls command is not sorted by plugin names (and changes order on repeating the command), e.g.:

```
$docker plugin ls
ID                  NAME                DESCRIPTION         ENABLED
c753fbc35b07        p1:latest           test plugin         false
8f818da86d15        p2:latest           test plugin         false
013f0525e658        p3:latest           test plugin         false
3e2fbda236fb        p5:latest           test plugin         false
917784fbd37c        p4:latest           test plugin         false
```

running the command again:
```
$ docker plugin ls
ID                  NAME                DESCRIPTION         ENABLED
917784fbd37c        p4:latest           test plugin         false
c753fbc35b07        p1:latest           test plugin         false
8f818da86d15        p2:latest           test plugin         false
013f0525e658        p3:latest           test plugin         false
3e2fbda236fb        p5:latest           test plugin         false
```

**Steps to reproduce the issue:**
1. Create a few plugins
2. Run `docker plugin ls` a few times and compare the output

**Describe the results you received:**
No specific order in the list of plugins

**Describe the results you expected:**
List of plugins sorted by name

### PR DESCRIPTION
**Pull request by adshmh**
**- What I did**
Sorted the output of `plugin list` command by plugin name. fixes #1164

**- How I did it**
Added sort functionality to `cli/command/plugin/list.go` and unit tests to `cli/command/plugin/list_test.go`

**- How to verify it**
1. Create multiple plugins
2. Run `docker plugin ls`
3. Output is sorted based on plugins' names

**- Description for the changelog**
docker plugin ls output is sorted based on plugin name

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: cli/command/plugin/list.go [hunk 1]
```diff
@@ -2,11 +2,15 @@ package plugin
 
 import (
 	"context"
+	"sort"
+
+	"vbom.ml/util/sortorder"
```
Comment (thaJeztah) [inline cli/command/plugin/list.go]: nit: can you group this import with the other imports below?

**Comment by thaJeztah** [comment]
ping @cpuguy83

File: cli/command/plugin/list.go [hunk 2]
```diff
@@ -17,6 +21,12 @@ type listOptions struct {
 	filter  opts.FilterOpt
 }
 
+type byName []*types.Plugin
```
Comment (cpuguy83) [inline cli/command/plugin/list.go]: Can we use `sort.Slice` instead of defining a type for this?

Comment (adshmh) [reply cli/command/plugin/list.go]: Thank you for the review. I will update the PR to use `sort.Slice`

File: cli/command/plugin/list.go [hunk 3]
```diff
@@ -17,6 +21,12 @@ type listOptions struct {
...
+
+func (n byName) Len() int           { return len(n) }
+func (n byName) Swap(i, j int)      { n[i], n[j] = n[j], n[i] }
+func (n byName) Less(i, j int) bool { return sortorder.NaturalLess(n[i].Name, n[j].Name) }
```
Comment (cpuguy83) [inline cli/command/plugin/list.go]: I'm not sure we need this lib. Should be able to compare strings directly.

Comment (cpuguy83) [reply cli/command/plugin/list.go]: Ok, makes sense.

Comment (thaJeztah) [reply cli/command/plugin/list.go]: Yes; it was added for natural sort
