### PR TITLE
fix formatting issue of encoded url

### LINKED ISSUE #2086: Getting context from a bad remote encoded URL prints improper error message
**Description**

If the remote URL is encoded, and if it errors out  - the printing of the formatted error message has a bug. 

**Steps to reproduce the issue:**
1. docker build "https://abc.blob.core.windows.net/a7fdb8ba2b604fc39fff7719c9c0443c-ep4eeithl2/source/201909120000/0f806a98-9168-4d71-a50b-101d30d0712f.tar.gz?sv=2018-03-28&sr=b&sig=G4KHMAO3wRxhrTILu6c5YC%2B0IYwKiJqbfqHCgTcS4wA%3D&se=2019-09-12T15%3A48%3A43Z&sp=cw"

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
unable to prepare context: unable to download remote context https://abc.blob.core.windows.net/a7fdb8ba2b604fc39fff7719c9c0443c-ep4eeithl2/source/201909120000/0f806a98-9168-4d71-a50b-101d30d07
12f.tar.gz?sv=2018-03-28&sr=b&sig=G4KHMAO3wRxhrTILu6c5YC%2B0IYwKiJqbfqHCgTcS4wA%3D&se=2019-09-12T15%3A48%3A43Z&sp=cw: failed to GET https://abc.blob.core.windows.net/a7fdb8ba2b604fc39fff7719c9
c0443c-ep4eeithl2/source/201909120000/0f806a98-9168-4d71-a50b-101d30d0712f.tar.gz?sv=2018-03-28&sr=b&sig=G4KHMAO3wRxhrTILu6c5YC[%!B(uint8=239) %!B(uint8=187) %!B(uint8=191) %!B(uint8=60) %!B(u
int8=63) %!B(uint8=120) %!B(uint8=109) %!B(uint8=108) %!B(uint8=32) %!B(uint8=118) %!B(uint8=101) %!B(uint8=114) %!B(uint8=115) %!B(uint8=105) %!B(uint8=111) %!B(uint8=110) %!B(uint8=61) %!B(u
int8=34) %!B(uint8=49) %!B(uint8=46) %!B(uint8=48) %!B(uint8=34) %!B(uint8=32) %!B(uint8=101) %!B(uint8=110) %!B(uint8=99) %!B(uint8=111) %!B(uint8=100) %!B(uint8=105) %!B(uint8=110) %!B(uint8
=103) %!B(uint8=61) %!B(uint8=34) %!B(uint8=117) %!B(uint8=116) %!B(uint8=102) %!B(uint8=45) %!B(uint8=56) %!B(uint8=34) %!B(uint8=63) %!B(uint8=62) %!B(uint8=60) %!B(uint8=69) %!B(uint8=114) 
%!B(uint8=114) %!B(uint8=111) %!B(uint8=114) %!B(uint8=62) %!B(uint8=60) %!B(uint8=67) %!B(uint8=111) %!B(uint8=100) %!B(uint8=101) %!B(uint8=62) %!B(uint8=65) %!B(uint8=117) %!B(uint8=116) %!
B(uint8=104) %!B(uint8=101) %!B(uint8=110) %!B(uint8=116) %!B(uint8=105) %!B(uint8=99) %!B(uint8=97) %!B(uint8=116) %!B(uint8=105) %!B(uint8=111) %!B(uint8=110) %!B(uint8=70) %!B(uint8=97) %!B
(uint8=105) %!B(uint8=108) %!B(uint8=101) %!B(uint8=100) %!B(uint8=60) %!B(uint8=47) %!B(uint8=67) %!B(uint8=111) %!B(uint8=100) %!B(uint8=101) %!B(uint8=62) %!B(uint8=60) %!B(uint8=77) %!B(ui
nt8=101) %!B(uint8=115) %!B(uint8=115) %!B(uint8=97) %!B(uint8=103) %!B(uint8=101) %!B(uint8=62) %!B(uint8=83) %!B(uint8=101) %!B(uint8=114) %!B(uint8=118) %!B(uint8=101) %!B(uint8=114) %!B(ui
nt8=32) %!B(uint8=102) %!B(uint8=97) %!B(uint8=105) %!B(uint8=108) %!B(uint8=101) %!B(uint8=100) %!B(uint8=32) %!B(uint8=116) %!B(uint8=111) %!B(uint8=32) %!B(uint8=97) %!B(uint8=117) %!B(uint
8=116) %!B(uint8=104) %!B(uint8=101) %!B(uint8=110) %!B(uint8=116) %!B(uint8=105) %!B(uint8=99) %!B(uint8=97) %!B(uint8=116) %!B(uint8=101) %!B(uint8=32) %!B(uint8=116) %!B(uint8=104) %!B(uint
8=101) %!B(uint8=32) %!B(uint8=114) %!B(uint8=101) %!B(uint8=113) %!B(uint8=117) %!B(uint8=101) %!B(uint8=115) %!B(uint8=116) %!B(uint8=46) %!B(uint8=32) %!B(uint8=77) %!B(uint8=97) %!B(uint8=
107) %!B(uint8=101) %!B(uint8=32) %!B(uint8=115) %!B(uint8=117) %!B(uint8=114) %!B(uint8=101) %!B(uint8=32) %!B(uint8=116) %!B(uint8=104) %!B(uint8=101) %!B(uint8=32) %!B(uint8=118) %!B(uint8=
97) %!B(uint8=108) %!B(uint8=117) %!B(uint8=101) %!B(uint8=32) %!B(uint8=111) %!B(uint8=102) %!B(uint8=32) %!B(uint8=65) %!B(uint8=117) %!B(uint8=116) %!B(uint8=104) %!B(uint8=111) %!B(uint8=1
14) %!B(uint8=105) %!B(uint8=122) %!B(uint8=97) %!B(uint8=116) %!B(uint8=105) %!B(uint8=111) %!B(uint8=110) %!B(uint8=32) %!B(uint8=104) %!B(uint8=101) %!B(uint8=97) %!B(uint8=100) %!B(uint8=1
01) %!B(uint8=114) %!B(uint8=32) %!B(uint8=105) %!B(uint8=115) %!B(uint8=32) %!B(uint8=102) %!B(uint8=111) %!B(uint8=114) %!B(uint8=109) %!B(uint8=101) %!B(uint8=100) %!B(uint8=32) %!B(uint8=9
9) %!B(uint8=111) %!B(uint8=114) %!B(uint8=114) %!B(uint8=101) %!B(uint8=99) %!B(uint8=116) %!B(uint8=108) %!B(uint8=121) %!B(uint8=32) %!B(uint8=105) %!B(uint8=110) %!B(uint8=99) %!B(uint8=10
8) %!B(uint8=117) %!B(uint8=100) %!B(uint8=105) %!B(uint8=110) %!B(uint8=103) %!B(uint8=32) %!B(uint8=116) %!B(uint8=104) %!B(uint8=101) %!B(uint8=32) %!B(uint8=115) %!B(uint8=105) %!B(uint8=1
03) %!B(uint8=110) %!B(uint8=97) %!B(uint8=116) %!B(uint8=117) %!B(uint8=114) %!B(uint8=101) %!B(uint8=46) %!B(uint8=10) %!B(uint8=82) %!B(uint8=101) %!B(uint8=113) %!B(uint8=117) %!B(uint8=10
1) %!B(uint8=115) %!B(uint8=116) %!B(uint8=73) %!B(uint8=100) %!B(uint8=58) %!B(uint8=98) %!B(uint8=53) %!B(uint8=51) %!B(uint8=52) %!B(uint8=51) %!B(uint8=100) %!B(uint8=55) %!B(uint8=97) %!B
(uint8=45) %!B(uint8=54) %!B(uint8=48) %!B(uint8=49) %!B(uint8=101) %!B(uint8=45) %!B(uint8=48) %!B(uint8=48) %!B(uint8=97) %!B(uint8=50) %!B(uint8=45) %!B(uint8=53) %!B(uint8=53) %!B(uint8=98
) %!B(uint8=50) %!B(uint8=45) %!B(uint8=54) %!B(uint8=57) %!B(uint8=49) %!B(uint8=98) %!B(uint8=53) %!B(uint8=99) %!B(uint8=48) %!B(uint8=48) %!B(uint8=48) %!B(uint8=48) %!B(uint8=48) %!B(uint
8=48) %!B(uint8=10) %!B(uint8=84) %!B(uint8=105) %!B(uint8=109) %!B(uint8=101) %!B(uint8=58) %!B(uint8=50) %!B(uint8=48) %!B(uint8=49) %!B(uint8=57) %!B(uint8=45) %!B(uint8=48) %!B(uint8=57) %
!B(uint8=45) %!B(uint8=49) %!B(uint8=50) %!B(uint8=84) %!B(uint8=50) %!B(uint8=49) %!B(uint8=58) %!B(uint8=51) %!B(uint8=55) %!B(uint8=58) %!B(uint8=48) %!B(uint8=53) %!B(uint8=46) %!B(uint8=5
5) %!B(uint8=53) %!B(uint8=51) %!B(uint8=55) %!B(uint8=53) %!B(uint8=48) %!B(uint8=55) %!B(uint8=90) %!B(uint8=60) %!B(uint8=47) %!B(uint8=77) %!B(uint8=101) %!B(uint8=115) %!B(uint8=115) %!B(
uint8=97) %!B(uint8=103) %!B(uint8=101) %!B(uint8=62) %!B(uint8=60) %!B(uint8=65) %!B(uint8=117) %!B(uint8=116) %!B(uint8=104) %!B(uint8=101) %!B(uint8=110) %!B(uint8=116) %!B(uint8=105) %!B(u
int8=99) %!B(uint8=97) %!B(uint8=116) %!B(uint8=105) %!B(uint8=111) %!B(uint8=110) %!B(uint8=69) %!B(uint8=114) %!B(uint8=114) %!B(uint8=111) %!B(uint8=114) %!B(uint8=68) %!B(uint8=101) %!B(ui
nt8=116) %!B(uint8=97) %!B(uint8=105) %!B(uint8=108) %!B(uint8=62) %!B(uint8=83) %!B(uint8=105) %!B(uint8=103) %!B(uint8=110) %!B(uint8=101) %!B(uint8=100) %!B(uint8=32) %!B(uint8=101) %!B(uin
t8=120) %!B(uint8=112) %!B(uint8=105) %!B(uint8=114) %!B(uint8=121) %!B(uint8=32) %!B(uint8=116) %!B(uint8=105) %!B(uint8=109) %!B(uint8=101) %!B(uint8=32) %!B(uint8=91) %!B(uint8=84) %!B(uint
8=104) %!B(uint8=117) %!B(uint8=44) %!B(uint8=32) %!B(uint8=49) %!B(uint8=50) %!B(uint8=32) %!B(uint8=83) %!B(uint8=101) %!B(uint8=112) %!B(uint8=32) %!B(uint8=50) %!B(uint8=48) %!B(uint8=49) 
%!B(uint8=57) %!B(uint8=32) %!B(uint8=49) %!B(uint8=53) %!B(uint8=58) %!B(uint8=52) %!B(uint8=56) %!B(uint8=58) %!B(uint8=52) %!B(uint8=51) %!B(uint8=32) %!B(uint8=71) %!B(uint8=77) %!B(uint8=84) %!B(uint8=93) %!B(uint8=32) %!B(uint8=109) %!B(uint8=117) %!B(uint8=115) %!B(uint8=116) %!B(uint8=32) %!B(uint8=98) %!B(uint8=101) %!B(uint8=32) %!B(uint8=97) %!B(uint8=102) %!B(uint8=116) %!B(uint8=101) %!B(uint8=114) %!B(uint8=32) %!B(uint8=115) %!B(uint8=105) %!B(uint8=103) %!B(uint8=110) %!B(uint8=101) %!B(uint8=100) %!B(uint8=32) %!B(uint8=115) %!B(uint8=116) %!B(uint8=97) %!B(uint8=114) %!B(uint8=116) %!B(uint8=32) %!B(uint8=116) %!B(uint8=105) %!B(uint8=109) %!B(uint8=101) %!B(uint8=32) %!B(uint8=91) %!B(uint8=84) %!B(uint8=104) %!B(uint8=117) %!B(uint8=44) %!B(uint8=32) %!B(uint8=49) %!B(uint8=50) %!B(uint8=32) %!B(uint8=83) %!B(uint8=101) %!B(uint8=112) %!B(uint8=32) %!B(uint8=50) %!B(uint8=48) %!B(uint8=49) %!B(uint8=57) %!B(uint8=32) %!B(uint8=50) %!B(uint8=49) %!B(uint8=58) %!B(uint8=51) %!B(uint8=55) %!B(uint8=58) %!B(uint8=48) %!B(uint8=53) %!B(uint8=32) %!B(uint8=71) %!B(uint8=77) %!B(uint8=84) %!B(uint8=93) %!B(uint8=60) %!B(uint8=47) %!B(uint8=65) %!B(uint8=117) %!B(uint8=116) %!B(uint8=104) %!B(uint8=101) %!B(uint8=110) %!B(uint8=116) %!B(uint8=105) %!B(uint8=99) %!B(uint8=97) %!B(uint8=116) %!B(uint8=105) %!B(uint8=111) %!B(uint8=110) %!B(uint8=69) %!B(uint8=114) %!B(uint8=114) %!B(uint8=111) %!B(uint8=114) %!B(uint8=68) %!B(uint8=101) %!B(uint8=116) %!B(uint8=97) %!B(uint8=105) %!B(uint8=108) %!B(uint8=62) %!B(uint8=60) %!B(uint8=47) %!B(uint8=69) %!B(uint8=114) %!B(uint8=114) %!B(uint8=111) %!B(uint8=114) %!B(uint8=62)]0IYwKiJqbfqHCgTcS4wA%!D(MISSING)&se=2019-09-12T15%!A(MISSING)48%!A(MISSING)43Z&sp=cw with status 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.: %!s(MISSING)

```

**Output of `docker info`:**

```
(paste your output here)
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc.)
  app: Docker Application (Docker Inc., v0.8.0)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I will have a PR out for the fix shortly

### PR DESCRIPTION
**Pull request by shahzzzam**
Fixes #2086 

**- What I did**
Since the `Errorf` uses `Sprintf`, we need to make sure that the `msg` which contains an encoded URL is also passed thru `Sprintf` , so that it is able to correctly map the arguments to the format string.

Something like this:
mage

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
Shih-Tzu-MP

### CODE REVIEW

File: cli/command/image/build/context.go [hunk 1]
```diff
@@ -242,9 +242,9 @@ func getWithStatusError(url string) (resp *http.Response, err error) {
 	body, err := ioutil.ReadAll(resp.Body)
 	resp.Body.Close()
 	if err != nil {
-		return nil, errors.Wrapf(err, msg+": error reading body")
+		return nil, errors.Wrapf(err, fmt.Sprintf("%s: error reading body", msg))
```
Comment (thaJeztah) [inline cli/command/image/build/context.go]: I think instead of this, this should be `errors.Wrap()` instead of `errors.Wrapf()`;

```suggestion
		return nil, errors.Wrap(err, msg+": error reading body")
```

File: cli/command/image/build/context.go [hunk 2]
```diff
@@ -242,9 +242,9 @@ func getWithStatusError(url string) (resp *http.Response, err error) {
...
 	}
-	return nil, errors.Errorf(msg+": %s", bytes.TrimSpace(body))
+	return nil, errors.Errorf("%s: %s", msg, bytes.TrimSpace(body))
```
Comment (thaJeztah) [inline cli/command/image/build/context.go]: This could use `errors.New()` instead

```suggestion
	return nil, errors.New(msg+": %s", bytes.TrimSpace(body))
```

Comment (thaJeztah) [reply cli/command/image/build/context.go]: Oh, never mind; ignore this one

**Comment by shahzzzam** [comment]
Thanks @thaJeztah, could you please help me figure why CI fails?

File: cli/command/image/build/context.go [hunk 3]
```diff
@@ -242,9 +242,9 @@ func getWithStatusError(url string) (resp *http.Response, err error) {
 	body, err := ioutil.ReadAll(resp.Body)
 	resp.Body.Close()
 	if err != nil {
-		return nil, errors.Wrapf(err, msg+": error reading body")
+		return nil, errors.Wrap(err, fmt.Sprintf("%s: error reading body", msg))
```
Comment (thaJeztah) [inline cli/command/image/build/context.go]: oh, perhaps I explained badly; this should either be;

```go
return nil, errors.Wrap(err, msg+": error reading body")
```

or

```go
return nil, errors.Wrapf(err, "%s: error reading body", msg)
```

Comment (shahzzzam) [reply cli/command/image/build/context.go]: Thank you!
