### PR TITLE
When nothing found in stack exit with exit code 1

### LINKED ISSUE #478: Docker stack ps  - Incorrect exit code
**Description**
When using the docker cli, it's consistent for the exit code to reflect the status of resources. 
exists - > 0
does not exists -> 1

However this behavior/pattern is not consistent across all CLI. For example:
```
~ $ docker stack ps missingstack
Nothing found in stack: missingstack
~ $ echo $?
0
```
Yet docker service will reply as expected:
```
~ $ docker service ps missingservice
no such services: missingservice
~ $ echo $?
1
~ $
```

**Steps to reproduce the issue:**
1. Create a docker swarm
2. Check if a stack exists `docker stack ps somestack`
3. Verify exit code: `echo $?`

**Describe the results you received:**
Exit code of `docker stack ps invalidstack` is `0`

**Describe the results you expected:**
Exit code of `docker stack ps invalidstack` is `1`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.1-ee-1
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   4dd6e94
 Built:        Sat Aug 12 01:18:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ee-1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   4dd6e94
 Built:        Sat Aug 12 01:25:18 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Same issue in `17.07.0-ce-rc4`

### PR DESCRIPTION
**Pull request by ripcurld0**
**- What I did**

close #478 

To keep on a consistent behaviour such as in docker-service-ps
if docker-stack-ps didn't find a given stack, the command line
should exit with exit code 1.

**- How I did it**

Instead of printing the error to `stdout`, return it.
This will automatically exit with error code 1.

**- How to verify it**

Run unit tests.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: cli/command/stack/ps_test.go [hunk 1]
```diff
@@ -60,9 +60,8 @@ func TestStackPsEmptyStack(t *testing.T) {
 	cmd := newPsCommand(fakeCli)
 	cmd.SetArgs([]string{"foo"})
 
-	assert.NoError(t, cmd.Execute())
-	assert.Equal(t, "", fakeCli.OutBuffer().String())
```
Comment (dnephin) [inline cli/command/stack/ps_test.go]: We could still check stdout is empty
