### PR TITLE
Permit '=' separator and '[ipv6]' in --add-host

### LINKED ISSUE #4648: ipv6 addresses cannot be used with the `--add-host` option
### Description

Using any ipv6 address with `--add-host` produces an error:

```
for "--add-host" flag: invalid IP address in add-host: <ipv6 address>
```

### Reproduce

```
$ docker run --add-host "host.docker.internal:[::1]" nginx

> invalid argument "host.docker.internal:[::1]" for "--add-host" flag: invalid IP address in add-host: "[::1]"
> See 'docker run --help'.
```

### Expected behavior

I am looking to be able to `curl -g -6 "http://[::1]:8080/"` from inside of the container. This is not possible, as `--add-host` does not allow specifying `[::1]` as the host's address.

### docker version

```bash
docker version
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     true
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
docker info
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/kai/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/kai/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/kai/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/kai/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/kai/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/kai/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/kai/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/kai/.docker/cli-plugins/docker-scout

Server:
 Containers: 33
  Running: 0
  Paused: 0
  Stopped: 33
 Images: 23
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.661GiB
 Name: linuxkit-a6b776a9963f
 ID: b7de54a1-66ec-4ab2-b3d6-ddea4d05bfdc
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: true
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

### Additional Info

daemon.json file:

```json
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": true,
  "fixed-cidr-v6": "fdaa::/16",
  "ip6tables": true,
  "ipv6": true
}
```

### PR DESCRIPTION
**Pull request by robmry**
Fixes #4648

**- What I did**

Make it easier to specify IPv6 addresses in the '--add-host' option by permitting 'host=ip' in addition to 'host:ip', and allowing square brackets around the address.

For example:

    --add-host=hostname:127.0.0.1
    --add-host=hostname:::1
    --add-host=hostname=::1
    --add-host=hostname:[::1]

**- How I did it**

To avoid compatibility problems, the CLI will replace an '=' separator with ':', and strip brackets, before sending the request to the API.

**- How to verify it**

New unit tests pass.

The `docker run` command sets up a `/etc/hosts` entry as expected when using '=' and brackets ...

```
# /usr/local/cli/cli/build/docker run -ti --add-host thishost=[::1] alpine sh
/ # cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
::1     thishost
172.18.0.2      43c134b9fad0
```

But `docker inspect` still shows the option with a ':' separator and no brackets ...

```
# /usr/local/cli/cli/build/docker inspect 43 -f '{{ .HostConfig.ExtraHosts }}'
[thishost:::1]
```

The same formats work for legacy `docker build`, `buildx` needs a separate change ...

```
root@6b6f43dcb70f:/go/src/github.com/docker/docker/a# cat Dockerfile
FROM alpine:latest
RUN ping -c1 something
RUN ping -c1 somethingv6

root@6b6f43dcb70f:/go/src/github.com/docker/docker/a# DOCKER_BUILDKIT=0 /usr/local/cli/cli/build/docker build --no-cache --add-host=something=8.8.8.8 --add-host somethingv6=[::1] .
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM alpine:latest
 ---> 3cc203321400
Step 2/3 : RUN ping -c1 something
 ---> Running in e4bbbe9f65d4
PING something (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=62 time=16.070 ms

--- something ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 16.070/16.070/16.070 ms
 ---> Removed intermediate container e4bbbe9f65d4
 ---> 13397ec9bb56
Step 3/3 : RUN ping -c1 somethingv6
 ---> Running in 39453415243e
PING somethingv6 (::1): 56 data bytes
64 bytes from ::1: seq=0 ttl=64 time=0.024 ms

--- somethingv6 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.024/0.024/0.024 ms
 ---> Removed intermediate container 39453415243e
 ---> e968e3d10d73
Successfully built e968e3d10d73
```

**- Description for the changelog**

Permit '=' separator and '[ipv6]' in --add-host

### CODE REVIEW

File: cli/command/container/opts.go [hunk 1]
```diff
@@ -210,7 +210,7 @@ func addFlags(flags *pflag.FlagSet) *containerOptions {
 	flags.SetAnnotation("cgroupns", "version", []string{"1.41"})
 
 	// Network and port publishing flag
-	flags.Var(&copts.extraHosts, "add-host", "Add a custom host-to-IP mapping (host:ip)")
+	flags.Var(&copts.extraHosts, "add-host", "Add a custom host-to-IP mapping (host:ip, or host=ip)")
```
Comment (thaJeztah) [inline cli/command/container/opts.go:213]: I'm slightly leaning towards "soft deprecating" the old format, and not advertising it too prominent.

In the docs, we could still make a mention of the old format (for users who are running an older version of the cli)

File: docs/reference/commandline/build.md [hunk 2]
```diff
@@ -462,6 +462,12 @@ more `--add-host` flags. This example adds a static address for a host named
 $ docker build --add-host docker:10.180.0.1 .
 ```
 
+For IPv6 addresses, the equivalent `host=ip` form may be clearer, for example:
```
Comment (thaJeztah) [inline docs/reference/commandline/build.md:465]: Related to my other comment; we can use the new format as default for the example, and make a mention of the old format.

(also /cc @dvdksn for suggestions)

**Review by thaJeztah — COMMENTED** [review]
just some quick comments from my comments phone ☺️

File: cli/command/container/opts.go (hunk 1 above)
Comment (robmry) [reply cli/command/container/opts.go:213]: Ah, yes - good idea! Will do, thank you.

File: docs/reference/commandline/build.md (hunk 2 above)
Comment (robmry) [reply docs/reference/commandline/build.md:465]: Ok, will do.

File: docs/reference/commandline/build.md [hunk 3]
```diff
@@ -454,20 +454,27 @@ Specifying the `--isolation` flag without a value is the same as setting `--isol
...
 the special `host-gateway` value for `--add-host`. In the following example,
 build containers resolve `host.docker.internal` to the host's gateway IP.
 
 ```console
-$ docker build --add-host host.docker.internal:host-gateway .
+$ docker build --add-host host.docker.internal=host-gateway .
+```
+
+IPv6 addresses may be enclosed in square brackets, and a `:` separator is
+accepted. For example:
```
Comment (dvdksn) [inline docs/reference/commandline/build.md:474]:
```suggestion
You can wrap an IPv6 address in square brackets.
`=` and `:` are both valid separators.
Both formats in the following example are valid:
```

File: docs/reference/commandline/run.md [hunk 4]
```diff
@@ -762,6 +762,12 @@ PING docker (93.184.216.34): 56 data bytes
 round-trip min/avg/max = 92.209/92.495/93.052 ms
 ```
 
+IPv6 addresses may be enclosed in square brackets:
```
Comment (dvdksn) [inline docs/reference/commandline/run.md:765]:
```suggestion
You can wrap an IPv6 address in square brackets:
```

File: docs/reference/commandline/run.md [hunk 5]
```diff
@@ -779,11 +785,17 @@ $ echo "hello from host!" > ./hello
 $ python3 -m http.server 8000
 Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
 $ docker run \
-  --add-host host.docker.internal:host-gateway \
+  --add-host host.docker.internal=host-gateway \
   curlimages/curl -s host.docker.internal:8000/hello
 hello from host!
 ```
 
+The `--add-host` flag will also accept a `:` separator, for example:
```
Comment (dvdksn) [inline docs/reference/commandline/run.md:793]:
```suggestion
The `--add-host` flag also accepts a `:` separator, for example:
```

File: man/docker-build.1.md [hunk 6]
```diff
@@ -78,10 +78,10 @@ set as the **URL**, the repository is cloned locally and then sent as the contex
    layers in tact, and one for the squashed version.
 
 **--add-host** []
-   Add a custom host-to-IP mapping (host:ip)
+   Add a custom host-to-IP mapping (host:ip, or host=ip)
 
-   Add a line to /etc/hosts. The format is hostname:ip.  The **--add-host**
-option can be set multiple times.
+   Add a line to /etc/hosts. The format is hostname:ip, or hostname=ip.  The
+**--add-host** option can be set multiple times.
```
Comment (dvdksn) [inline man/docker-build.1.md:84]:
```suggestion
   Add a line to /etc/hosts. The format is hostname:ip, or hostname=ip.
   The **--add-host** option can be set multiple times.
```

File: man/docker-run.1.md [hunk 7]
```diff
@@ -121,10 +121,10 @@ executables expect) and pass along signals. The **-a** option can be set for
 each of stdin, stdout, and stderr.
 
 **--add-host**=[]
-   Add a custom host-to-IP mapping (host:ip)
+   Add a custom host-to-IP mapping (host:ip, or host=ip)
 
-   Add a line to /etc/hosts. The format is hostname:ip.  The **--add-host**
-option can be set multiple times.
+   Add a line to /etc/hosts. The format is hostname:ip, or hostname=ip. The
+**--add-host** option can be set multiple times.
```
Comment (dvdksn) [inline man/docker-run.1.md:127]:
```suggestion
   Add a line to /etc/hosts. The format is hostname:ip, or hostname=ip.
   The **--add-host** option can be set multiple times.
```

**Review by dvdksn — COMMENTED** [review]
looks good, a couple suggestions

File: docs/reference/commandline/build.md (hunk 3 above)
Comment (robmry) [reply docs/reference/commandline/build.md]: That's better! Thank you ... and ditto all the rest, I've pushed the changes.

File: docs/reference/commandline/run.md (hunk 4 above)
Comment (robmry) [reply docs/reference/commandline/run.md]: Done.

File: docs/reference/commandline/run.md (hunk 5 above)
Comment (robmry) [reply docs/reference/commandline/run.md]: Done.

File: man/docker-build.1.md (hunk 6 above)
Comment (robmry) [reply man/docker-build.1.md]: Done.

**Review by dvdksn — APPROVED** [review]
docs lgtm 👍🏻

File: man/docker-build.1.md [hunk 8]
```diff
@@ -78,10 +78,10 @@ set as the **URL**, the repository is cloned locally and then sent as the contex
    layers in tact, and one for the squashed version.
 
 **--add-host** []
-   Add a custom host-to-IP mapping (host:ip)
+   Add a custom host-to-IP mapping (host:ip, or host=ip)
```
Comment (thaJeztah) [inline man/docker-build.1.md:81]: Micro-nit; perhaps swap the order to put the preference on `=`;

```markdown
   Add a custom host-to-IP mapping (host=ip, or host:ip)
```

File: man/docker-run.1.md [hunk 9]
```diff
@@ -121,10 +121,10 @@ executables expect) and pass along signals. The **-a** option can be set for
 each of stdin, stdout, and stderr.
 
 **--add-host**=[]
-   Add a custom host-to-IP mapping (host:ip)
+   Add a custom host-to-IP mapping (host:ip, or host=ip)
```
Comment (thaJeztah) [inline man/docker-run.1.md:124]: Same here

File: docs/reference/commandline/run.md [hunk 10]
```diff
@@ -779,11 +785,17 @@ $ echo "hello from host!" > ./hello
...
-  --add-host host.docker.internal:host-gateway \
+  --add-host host.docker.internal=host-gateway \
   curlimages/curl -s host.docker.internal:8000/hello
 hello from host!
 ```
 
+The `--add-host` flag also accepts a `:` separator, for example:
+
+```console
+$ docker run --add-host=docker:93.184.216.34 --rm -it alpine
```
Comment (thaJeztah) [inline docs/reference/commandline/run.md:796]: For examples, I try to use names that help identify they're "custom" values (and for illustrative purpose). Using `docker` (or `hostname` as was used elsewhere) _could_ be confused for "docker" being some special value.

Something like `my-hostname` could perhaps work;

```bash
$ docker run --add-host=my-hostname:93.184.216.34 --rm -it alpine
```

I'm curious where the `93.184.216.34` address came from; it 

It's also good to make an example "do" something. In this case, we want to illustrate that adding the hostname allows the hostname to be resolved inside the container. I'm curious where the `93.184.216.34` IP-address came from, but if we want to be sure `ping` works, perhaps we should use a well-known IP-address, e.g. `8.8.8.8`;

```bash
$ docker run --add-host=my-hostname:8.8.8.8 --rm alpine ping -c1 my-hostname
PING my-hostname (8.8.8.8): 56 data bytes
64 bytes from 8.8.8.8: seq=0 ttl=63 time=14.995 ms

--- my-hostname ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 14.995/14.995/14.995 ms
```

The advantage of `ping` of course is that (most) users would understand what we're doing. Alternatively (if we don't want to depend on networking, and only illustrate the actual effect), we could show that the entry was added to `/etc/hosts` inside the container (but not sure if that's to be considered too much an implementation details);

```bash
$ docker run --add-host=my-hostname:8.8.8.8 --rm alpine sh -c 'cat /etc/hosts | grep my-hostname'
8.8.8.8	my-hostname
````

I considered `nslookup` as alternative, but :see_no_evil: of course that doesn't work with `/etc/hosts`, so we'd need something like `getent`, which probably isn't ideal (not as widely used; at least I had to quickly lookup the right way to use it :joy:)

```bash
$ docker run --add-host=my-hostname:8.8.8.8 --rm alpine getent ahosts my-hostname
8.8.8.8         STREAM my-hostname
8.8.8.8         DGRAM  my-hostname
```

Comment (thaJeztah) [reply docs/reference/commandline/run.md:796]: Oh! Before I forget (and probably not needed for these examples); if we use example _domains_ in our docs; always make sure to use one of the designated domains for that purpose, such as `*.example.com`, `*.example.org` (https://www.rfc-editor.org/rfc/rfc6761.html).

(We've had cases where we used some (assumed) made-up domain, which... was in active use 😬)

File: opts/hosts.go [hunk 11]
```diff
@@ -161,21 +161,53 @@ func ParseTCPAddr(tryAddr string, defaultAddr string) (string, error) {
...
+// to be a valid ip (IPv4 or IPv6). The address may be enclosed in square
+// brackets.
 //
-// TODO(thaJeztah): remove client-side validation, and delegate to the API server.
+// For example:
+//
+//	hostname:127.0.0.1
+//	hostname:::1
+//	hostname=::1
+//	hostname:[::1]
```
Comment (thaJeztah) [inline opts/hosts.go:174]: See my other comment; perhaps use `my-hostname` or something similar, to prevent `hostname` being confused for a special keyword.

File: opts/hosts.go [hunk 12]
```diff
@@ -161,21 +161,53 @@ func ParseTCPAddr(tryAddr string, defaultAddr string) (string, error) {
...
+		// permit it for IPv4 as well; we don't know the address family here, but it's
+		// unambiguous).
+		if len(v) > 2 && v[0] == '[' && v[len(v)-1] == ']' {
+			v = v[1 : len(v)-1]
+		}
+		// ValidateIPAddress returns the address in canonical form (for example,
+		// 0:0:0:0:0:0:0:1 -> ::1). But, stick with the original form, to avoid
+		// surprising a user who's expecting to see the address they supplied in the
+		// output of 'docker inspect' or '/etc/hosts'.
 		if _, err := ValidateIPAddress(v); err != nil {
```
Comment (thaJeztah) [inline opts/hosts.go:205]: Not for this PR, but still considering using the normalised variant; that would potentially avoid duplicates;

```bash
docker run --add-host=my-hostname:0:0:0:0:0:0:0:1 --add-host=my-hostname:::1 --rm alpine sh -c 'cat /etc/hosts | grep my-hostname'
0:0:0:0:0:0:0:1	my-hostname
::1	my-hostname
```

File: docs/reference/commandline/build.md [hunk 13]
```diff
@@ -454,20 +454,28 @@ Specifying the `--isolation` flag without a value is the same as setting `--isol
...
-You can add other hosts into a container's `/etc/hosts` file by using one or
-more `--add-host` flags. This example adds a static address for a host named
-`docker`:
+You can add other hosts into a build container's `/etc/hosts` file by using one
+or more `--add-host` flags. This example adds static addresses for hosts named
+`docker` and `dockerv6`:
 
 ```console
-$ docker build --add-host docker:10.180.0.1 .
+$ docker build --add-host docker=10.180.0.1 --add-host dockerv6=2001:db8::33 .
```
Comment (thaJeztah) [inline docs/reference/commandline/build.md:462]: While we're updating these, perhaps also update the example hostnames (per my other comment)

File: opts/hosts_test.go [hunk 14]
```diff
@@ -146,34 +148,152 @@ func TestParseInvalidUnixAddrInvalid(t *testing.T) {
...
+			expectedErr: `invalid IP address in add-host: "::1]"`,
+		},
+		{
+			doc:         "Missing address, colon sep",
+			input:       `missing.address.colon:`,
+			expectedErr: `invalid IP address in add-host: ""`,
+		},
+		{
+			doc:         "Missing address, eq sep",
+			input:       `missing.address.eq=`,
```
Comment (thaJeztah) [inline opts/hosts_test.go:268]: For tests, I also tend to use the special domain-names (`example.com`, `example.org`, and/or the `.invalid` TLDs) _where possible_ of course.

Unlikely to happen for a unit-test, but I've had some test-cases in other repositories happily sending requests to some random domains that actually existed 🙈

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks! I left some comments; non-critical, but some would probably be good to address before merging (happy to hear your thoughts!)

File: man/docker-build.1.md (hunk 8 above)
Comment (robmry) [reply man/docker-build.1.md:81]: Yes, will do. (Also makes it consistent with other text that I'd already fixed.)

File: man/docker-run.1.md (hunk 9 above)
Comment (robmry) [reply man/docker-run.1.md:124]: Will do.

File: docs/reference/commandline/run.md (hunk 10 above)
Comment (robmry) [reply docs/reference/commandline/run.md:796]: `docker:93.184.216.34` was already used in the ping example (the address was introduced in https://github.com/docker/cli/commit/47ba76afb159273e35326bd0cb548e960c51fbc7 ) ... so I kept it, but something like `my-hostname:8.8.8.8` looks better, I'll change it.

"ping" seems like a nice simple/clear example, and with `8.8.8.8` it should normally work, so I'll keep it.

File: opts/hosts.go (hunk 11 above)
Comment (robmry) [reply opts/hosts.go:174]: Makes sense - will do!

File: opts/hosts.go (hunk 12 above)
Comment (robmry) [reply opts/hosts.go:205]: Ah, yes, I hadn't thought about duplicates - was more worried about second-guessing the user. I think only the last entry will be used if there are duplicates. I suppose we could use the canonical form to check for duplicates internally, and preserve the user's address in the file.

File: docs/reference/commandline/build.md (hunk 13 above)
Comment (robmry) [reply docs/reference/commandline/build.md:462]: Will do.

File: opts/hosts_test.go (hunk 14 above)
Comment (robmry) [reply opts/hosts_test.go:268]: Ah, yes - that'd be better, will do.

**Comment by thaJeztah** [comment]
Looks like this needs a rebase 🙈

File: cli/command/container/opts.go [hunk 15]
```diff
@@ -210,7 +210,7 @@ func addFlags(flags *pflag.FlagSet) *containerOptions {
 	flags.SetAnnotation("cgroupns", "version", []string{"1.41"})
 
 	// Network and port publishing flag
-	flags.Var(&copts.extraHosts, "add-host", "Add a custom host-to-IP mapping (host:ip)")
+	flags.Var(&copts.extraHosts, "add-host", "Add a custom host-to-IP mapping (host=ip)")
```
[the remark this answers is not in the document]
Comment (robmry) [reply cli/command/container/opts.go:213]: Yes - sure, I'll do that now ...

**Comment by thaJeztah** [comment]
Let's bring this one in; looks like buildx will get this format in v0.13.0, so there will be some period where they don't match, but don't think there's a good way around that (without https://github.com/docker/buildx/pull/2149)
