### PR TITLE
fix: restore os.Args after plugin completion and fix error return

### LINKED ISSUE #6816: fix: restore os.Args after plugin completion and fix error return
**Description**

This PR fixes two issues in the plugin manager:

1. **Fix error return value**: The plugin stub was returning the wrong error variable when flag parsing failed
2. **Restore os.Args after plugin completion**: The global os.Args was being modified during plugin completion but not restored, which could cause side effects in subsequent code

**Files changed:**

- `cli-plugins/manager/cobra.go`:
  - Line 50: Return `perr` instead of `err`
  - Lines 63-66: Save and restore original `os.Args` using defer

- `cli-plugins/manager/cobra_test.go`:
  - Add tests for the above fixes

### PR DESCRIPTION
**Pull request by luojiyin1987**
**- What I did**

Fix two issues in the plugin manager:

1. Fix error return value: The plugin stub was returning the wrong error variable when flag parsing failed
2. Restore os.Args after plugin completion: The global os.Args was being modified during plugin completion but not restored, which could cause side effects in subsequent code

**- How I did it**

1. Changed the error return from `err` to `perr` when flag parsing fails
2. Added code to save the original `os.Args` before modification and use `defer` to restore it
3. Added comprehensive tests to verify both fixes

**- Files changed:**

| File | Change |
|------|--------|
| `cli-plugins/manager/cobra.go` | Fix error return + restore os.Args |
| `cli-plugins/manager/cobra_test.go` | Add regression tests |

**- How to verify it**

The new tests verify both scenarios.

**- Description for the changelog**

```text
Fix os.Args restoration and error handling in plugin manager
```

Fixes #6816

### CODE REVIEW

File: cli-plugins/manager/cobra.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ func AddPluginCommandStubs(dockerCLI config.Provider, rootCmd *cobra.Command) (e
 					flags.SetOutput(nil)
 					perr := flags.Parse(args)
 					if perr != nil {
-						return err
+						return perr
```
Comment (thaJeztah) [inline cli-plugins/manager/cobra.go]: Nice catch; while updating; perhaps just inline it;


```go
if err := flags.Parse(args); err != nil {
	return err
```

File: cli-plugins/manager/cobra_test.go [hunk 2]
```diff
@@ -24,3 +29,47 @@ func TestPluginResourceAttributesEnvvar(t *testing.T) {
...
+
+	originalArgs := []string{"docker", "image", "ls"}
+	os.Args = append([]string(nil), originalArgs...)
+
+	_, directive := cmd.ValidArgsFunction(cmd, []string{"--all"}, "alp")
+	assert.Equal(t, directive, cobra.ShellCompDirectiveError)
+	assert.DeepEqual(t, os.Args, originalArgs)
+}
+
+func preparePluginStubCommand(t *testing.T, metadata string) *cobra.Command {
```
Comment (thaJeztah) [inline cli-plugins/manager/cobra_test.go]: Looks like my IDE (and possibly linters) has trouble detecting that the returned command will never be `nil` (due to the asserts); it's probably OK to just return the errors instead

File: cli-plugins/manager/cobra_test.go [hunk 3]
```diff
@@ -24,3 +29,47 @@ func TestPluginResourceAttributesEnvvar(t *testing.T) {
...
+	t.Helper()
+	pluginCommandStubsOnce = sync.Once{}
+
+	dir := fs.NewDir(t, t.Name(),
+		fs.WithFile("docker-testplugin", "#!/bin/sh\nprintf '%s' '"+metadata+"'\n", fs.WithMode(0o777)),
+	)
+	t.Cleanup(func() { dir.Remove() })
```
Comment (thaJeztah) [inline cli-plugins/manager/cobra_test.go]: I know we use the `fs` package still in some other places in this package, but I'm .. slightly trying to get rid of it (in most cases it's overkill); this one can probably be simplified using stdlib;


Also looks like we don't use the `metadata` anywhere for assertions, so we could just make this all "static" (until there's a specific reason to customise it);

```go
	tmpDir := t.TempDir()
	const cliPlugin = `
#!/bin/sh
printf '%s' '{"SchemaVersion":"0.1.0","Vendor":"e2e-testing"}'
`
	err := os.WriteFile(filepath.Join(tmpDir, "docker-testplugin"), []byte(cliPlugin), 0o777)
```

File: cli-plugins/manager/cobra_test.go [hunk 4]
```diff
@@ -24,3 +29,47 @@ func TestPluginResourceAttributesEnvvar(t *testing.T) {
...
+
+	cli := test.NewFakeCli(nil)
+	cli.SetConfigFile(&configfile.ConfigFile{
+		CLIPluginsExtraDirs: []string{dir.Path()},
+	})
```
Comment (thaJeztah) [inline cli-plugins/manager/cobra_test.go]: Probably fine here to simplify and just patch the config;


```go
cli.ConfigFile().CLIPluginsExtraDirs = []string{tmpDir}
```

File: cli-plugins/manager/cobra.go (hunk 1 above)
Comment (luojiyin1987) [reply cli-plugins/manager/cobra.go]: Applied in 402b1db. I switched this to the inline form:

```go
if err := flags.Parse(args); err != nil {
	return err
}
```

File: cli-plugins/manager/cobra_test.go (hunk 3 above)
Comment (luojiyin1987) [reply cli-plugins/manager/cobra_test.go]: Applied in 402b1db. I removed `gotest.tools/fs` in this helper and switched to `t.TempDir()` + `os.WriteFile(...)`, with static plugin metadata.

File: cli-plugins/manager/cobra_test.go (hunk 2 above)
Comment (luojiyin1987) [reply cli-plugins/manager/cobra_test.go]: Applied in 402b1db. I changed the helper to return `(*cobra.Command, error)`, and callers now handle/assert the returned error explicitly.

File: cli-plugins/manager/cobra_test.go (hunk 4 above)
Comment (luojiyin1987) [reply cli-plugins/manager/cobra_test.go]: Applied in 402b1db. I simplified this to patch config directly:

```go
cli.ConfigFile().CLIPluginsExtraDirs = []string{tmpDir}
```

**Comment by luojiyin1987** [comment]
Updated in commit 402b1db and addressed all review points (inline parse error handling, helper returns error, stdlib temp file setup, and config patch simplification). I also resolved the review threads.\n\n@thaJeztah could you please take another look when you have a moment? Thanks!

File: cli-plugins/manager/cobra_test.go [hunk 5]
```diff
@@ -24,3 +28,53 @@ func TestPluginResourceAttributesEnvvar(t *testing.T) {
...
+
+	err = cmd.RunE(cmd, []string{"--definitely-not-a-real-flag"})
+	assert.ErrorContains(t, err, "unknown flag: --definitely-not-a-real-flag")
+}
+
+func TestPluginStubCompletionRestoresOSArgs(t *testing.T) {
+	cmd, err := preparePluginStubCommand(t)
+	assert.NilError(t, err)
+
+	originalArgs := []string{"docker", "image", "ls"}
```
[the remark this answers is not in the document]
Comment (thaJeztah) [reply cli-plugins/manager/cobra_test.go:47]: heh; yeah, probably won't hurt to do; I can do a quick fix
