### PR TITLE
fixes 1492: tty initial size error

### LINKED ISSUE #1492: initial windows size of docker exec -it is too small
**Description**
initial windows size of `docker exec -it` is too small, I need to resize the window.
This is too inconvenient for me.

**Steps to reproduce the issue:**
1. docker exec -it k8s_nginxgateway_apigateway-pxwj9_default_430f8bb0-dcb3-11e8-a770-00163e0aec56_0 /bin/bash
2. vim /usr/local/nginx/conf/nginx.conf

**Describe the results you received:**
t0gq 6tu a s6 32wesg

**Describe the results you expected:**
the vim window size should be equal to the window's size.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Output of `docker info`:**

```
Containers: 25
 Running: 24
 Paused: 0
 Stopped: 1
Images: 75
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-105-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: iz2zef7rx1lvm90vsghh9qz.acmcoder.mmttnn
ID: OQTM:H2HJ:U2XT:WKLC:U4ZY:EHVI:QTXN:W4GK:QDA4:LUDJ:LFN7:WG3V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Aliyun cloud

### PR DESCRIPTION
**Pull request by lifubang**
Signed-off-by: Lifubang <lifubang@acmcoder.com>

fixes #1492.

For Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64), Docker version 17.12.0-ce, build c97c6d6 / 18.03.0-ce, build 0520e24
When I run: `docker exec -it ubuntu /bin/bash`
The tty's size is small than window's size.
```
root@iZ2zeesy3n96esegm7tue0Z:~# docker exec -it ubuntu /bin/bash
root@97b3e229a701:/# ls -a
.   .dockerenv  bin   dev  home  lib64  mnt  proc  run   srv  tmp  var
..  .r          boot  etc  lib   media  opt  root  sbin  sys  usr
```
After I fix the bug:
```
root@iZ2zeesy3n96esegm7tue0Z:~# ./docker-linux-amd64 exec -it ubuntu /bin/bash
root@97b3e229a701:/# ls -a
.  ..  .dockerenv  .r  bin  boot  dev  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```
If not fix this bug, it's too inconvenient for me to use docker exec -it.

**- What I did**
1. Fix tty initial size error
I think it's a bug of dockerd, but for previous dockerd edition, I think we can fix it in cli.
2. Fix when we use --debug flag, the first shell prompt don't return to the head of line when we got an error in func resizeTtyTo!

**- How I did it**
~~func MonitorTtySize in file cli/command/container/tty.go~~
~~I move the call resizeTty() to last and run it asynchronously.~~
1. Because in sometimes when dockercli call tty resize, the exec have not finished yet. Then we got a message "Error response from daemon: no such exec", but we ignore it, so we need to throw this error and deal with it after 10 milliseconds.
2. Add `\r` when logrus.Debugf.

**- How to verify it**
It's convenient for me to use docker exec -it.
I don't need to resize the window.

**- Description for the changelog**
fixes tty initial size error

**- I have no more cute animal now**
**Before fix:**
vim /etc/mime.types
sk j _1irw za2kc78iody5

**After fix:**
vim /etc/mime.types
x z0 r5jg_i4h x6m2bny 4

### CODE REVIEW

**Comment by lifubang** [comment]
@thaJeztah it is the duplicate copy of #1380, PTAL.

File: cli/command/container/tty.go [hunk 1]
```diff
@@ -34,19 +34,48 @@ func resizeTtyTo(ctx context.Context, client client.ContainerAPIClient, id strin
 	}
 
 	if err != nil {
-		logrus.Debugf("Error resize: %s", err)
+		logrus.Debugf("Error resize: %s\r", err)
```
Comment (kolyshkin) [inline cli/command/container/tty.go]: What is the reason for adding `\r` here?

Comment (lifubang) [reply cli/command/container/tty.go]: @kolyshkin Nice to see you again ^_^ 
Thanks for your review. It's because that:
```
root@iZ2zeesy3n96esegm7tue0Z:~# docker --debug exec -it k8s_nginxgateway_apigateway-p46ch_default_2de895e0-e8a8-11e8-badf-00163e0af11c_0 /bin/bash
DEBU[0000] Error resize: Error response from daemon: no such exec 
                                                                  root@apigateway-p46ch:/# ls
bin   dev  home  lib64  mnt  proc  run   srv  t    usr
boot  etc  lib   media  opt  root  sbin  sys  tmp  var
root@apigateway-p46ch:/#
```
When we use `--debug`, the first shell prompt don't return to the head of line?

Comment (kolyshkin) [reply cli/command/container/tty.go]: Nice catch! I've definitely seen it in the past.

Maybe add a comment why `\r` is there to the patch description, so anyone doing `git blame` can find the reason why.

Comment (lifubang) [reply cli/command/container/tty.go]: No code change, modify patch description now. Thanks.

File: cli/command/container/tty.go [hunk 2]
```diff
@@ -34,19 +34,48 @@ func resizeTtyTo(ctx context.Context, client client.ContainerAPIClient, id strin
...
-	resizeTty()
+// safeResizeTty is to resize the tty's size safely
+func safeResizeTty(ctx context.Context, cli command.Cli, id string, isExec bool, resizeTtyFunc func(ctx context.Context, cli command.Cli, id string, isExec bool) error) {
+	rttyFunc := resizeTtyFunc
+	if rttyFunc == nil {
+		rttyFunc = resizeTty
+	}
+	err := rttyFunc(ctx, cli, id, isExec)
+	if err != nil {
+		retryTimes := 5
```
Comment (thaJeztah) [inline cli/command/container/tty.go]: The loop looked a bit complicated to me; wondering; would this work? (pls double-check; it's just a very quick draft)

```go
go func() {
	var err error
	for retry := 0; retry < 5; retry++ {
		time.Sleep(10 * time.Millisecond)
		err = rttyFunc(ctx, cli, id, isExec)
		if err == nil {
			break
		}
	}
	if err != nil {
		fmt.Fprintln(cli.Err(), "Resize tty error, we'll use a default size. You can resize the tty size manually.")
	}
}()
```

File: cli/command/container/client_test.go [hunk 3]
```diff
@@ -12,20 +12,24 @@ import (
...
-	containerCopyFromFunc func(container, srcPath string) (io.ReadCloser, types.ContainerPathStat, error)
-	logFunc               func(string, types.ContainerLogsOptions) (io.ReadCloser, error)
-	waitFunc              func(string) (<-chan container.ContainerWaitOKBody, <-chan error)
-	containerListFunc     func(types.ContainerListOptions) ([]types.Container, error)
-	containerExportFunc   func(string) (io.ReadCloser, error)
-	Version               string
+	inspectFunc         func(string) (types.ContainerJSON, error)
+	execInspectFunc     func(execID string) (types.ContainerExecInspect, error)
+	execCreateFunc      func(container string, config types.ExecConfig) (types.IDResponse, error)
+	createContainerFunc func(config *container.Config,
```
[the remark this answers is not in the document]
Comment (lifubang) [reply cli/command/container/client_test.go]: Because in circle:lint, there is an error:
cli/command/container/client_test.go:18::warning: line is 201 characters (lll),
so I need to force this wrap, or else ci will get an error.

File: cli/command/container/tty.go [hunk 4]
```diff
@@ -34,19 +34,48 @@ func resizeTtyTo(ctx context.Context, client client.ContainerAPIClient, id strin
...
-	}
+// resizeTty is to resize the tty with cli out's tty size
+func resizeTty(ctx context.Context, cli command.Cli, id string, isExec bool) error {
+	height, width := cli.Out().GetTtySize()
+	return resizeTtyTo(ctx, cli.Client(), id, height, width, isExec)
+}
 
-	resizeTty()
+// safeResizeTty is to resize the tty's size safely
+func safeResizeTty(ctx context.Context, cli command.Cli, id string, isExec bool, resizeTtyFunc func(ctx context.Context, cli command.Cli, id string, isExec bool) error) {
```
[the remark this answers is not in the document]
Comment (lifubang) [reply cli/command/container/tty.go]: Yes, I change it to initTtySize, because this function is used to init the tty's size.

File: cli/command/container/tty.go (hunk 2 above)
Comment (lifubang) [reply cli/command/container/tty.go]: In the beginning after I wrote this code, I had the same feeling as you. But I have used it for about half a year, it works fine for my team.
But I can't promise it is the perfect solution, if some one have more simple way, please tell us, thanks. @kolyshkin Please take a look and help me to check this code, thank you very much.

Comment (lifubang) [reply cli/command/container/tty.go]: I will test this code.

Comment (lifubang) [reply cli/command/container/tty.go]: Congratulations, this quick draft works very well.

File: cli/command/container/tty.go [hunk 5]
```diff
@@ -34,19 +34,44 @@ func resizeTtyTo(ctx context.Context, client client.ContainerAPIClient, id strin
...
+	if rttyFunc == nil {
+		rttyFunc = resizeTty
+	}
+	err := rttyFunc(ctx, cli, id, isExec)
+	if err != nil {
+		go func() {
+			var err error
+			for retry := 0; retry < 5; retry++ {
+				time.Sleep(10 * time.Millisecond)
+				err = rttyFunc(ctx, cli, id, isExec)
```
Comment (silvin-lubecki) [inline cli/command/container/tty.go]: nit: 
```go
if err = rttyFunc(ctx, cli, id, isExec); err == nil{
    break
}
```

Comment (lifubang) [reply cli/command/container/tty.go]: Thanks. I also changed the line 54:
https://github.com/docker/cli/blob/5017d5fbc08f56ca604bb501ee8ff8bfa701fd07/cli/command/container/tty.go#L54

File: cli/command/container/tty.go [hunk 6]
```diff
@@ -34,19 +34,42 @@ func resizeTtyTo(ctx context.Context, client client.ContainerAPIClient, id strin
...
+		go func() {
+			var err error
+			for retry := 0; retry < 5; retry++ {
+				time.Sleep(10 * time.Millisecond)
+				if err = rttyFunc(ctx, cli, id, isExec); err == nil {
+					break
+				}
+			}
+			if err != nil {
+				fmt.Fprintln(cli.Err(), "Resize tty error, we'll use a default size. You can resize the tty size manually.")
```
Comment (silvin-lubecki) [inline cli/command/container/tty.go]: What about `fmt.Println(cli.Err(), "error resizing tty, falling back to default size")` ?

Comment (thaJeztah) [reply cli/command/container/tty.go]: Ah, yes, good suggestion; perhaps "failed to" or "unable to" (I think we generally use `failed to` for such things)

```suggestion
				fmt.Fprintln(cli.Err(), "failed to resize tty, using default size")
```

File: cli/command/container/client_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (thaJeztah) [reply cli/command/container/client_test.go]: ah! hm that's a pity (as it's not related to this change 😞)

File: cli/command/container/tty.go (hunk 6 above)
Comment (lifubang) [reply cli/command/container/tty.go]: Yes, but I can't use commit suggestion button in this conversation because I also need to update the test case.
