### PR TITLE
fix insecure manifest inspect with restrictive certs perms

### LINKED ISSUE #1358: "docker manifest inspect --insecure" doesn't work
**Description**

I have a local (insecure) registry for debugging purposes. But I cannot run `manifest inspect` against it, even with `--insecure`.

```
$ docker -D manifest inspect --insecure 172.17.0.4:5000/foo:latest
DEBU[0000] hostDir: /etc/docker/certs.d/172.17.0.4:5000 
DEBU[0000] endpoints for 172.17.0.4:5000/foo:latest: [] 
DEBU[0000] hostDir: /etc/docker/certs.d/172.17.0.4:5000 
DEBU[0000] endpoints for 172.17.0.4:5000/foo:latest: [] 
open /etc/docker/certs.d/172.17.0.4:5000: permission denied
```

**Steps to reproduce the issue:**

Just run `docker -D manifest inspect --insecure 172.17.0.4:5000/foo:latest`.

The registry and the image don't actually need to exist to hit the problem since it occurs before any sockets are opened etc (according to my quick look over the strace logs).

**Describe the results you received:**

```
open /etc/docker/certs.d/172.17.0.4:5000: permission denied
```

**Describe the results you expected:**

The manifest to be printed.

**Additional information you deem important (e.g. issue happens only occasionally):**

The directory `/etc/docker/certs.d` doesn't exist, but in any case the permissions on `/etc/docker` are `0700`, also it seems odd to rely only on a system wide directory here. I couldn't find any setting or config file option which would redirect this to e.g. `~/.docker/certs.d`.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:33 2018
 OS/Arch:           linux/amd64
 Experimental:      true

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:38 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

Also reproduced with 96dba79d99d69df9adc67b230d9dd39849733ef2 (recent master).

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 178
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.14.0-3-amd64
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.53GiB
Name: bokrug
ID: AU33:BO7D:7VGM:MOLB:RSDF:IBRV:GCWT:THHM:OEVM:TX3C:BNLM:WHAR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 67
 System Time: 2018-09-10T10:09:15.802266701+01:00
 EventsListeners: 0
Username: ijc25
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Native Linux (Debian) running docker-ce packages from `download.docker.com` apt repo.

### PR DESCRIPTION
**Pull request by clnperez**
If, for some reason, the certs directory has permissions that are
inaccessible by docker, we should still be able to fetch manifests using
the `insecure` flag.

Since the cli doesn't access the engine's list of insecure registries,
the registry client should make a singleton list of the registry being queried with the
`insecure` flag.

Closes #1358

Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

### CODE REVIEW

File: cli/registry/client/fetcher.go [hunk 1]
```diff
@@ -262,12 +262,18 @@ func (c *client) iterateEndpoints(ctx context.Context, namedRef reference.Named,
...
 	repoInfo, err := registry.ParseRepositoryInfo(namedRef)
 	if err != nil {
 		return nil, err
 	}
-	registryService, err := registry.NewService(registry.ServiceOptions{})
+
+	serviceOpts := registry.ServiceOptions{}
+	if insecure {
+		logrus.Debugf("allowing insecure registry for: %s", reference.Domain(namedRef))
+		serviceOpts.InsecureRegistries = []string{reference.Domain(namedRef)}
```
Comment (thaJeztah) [inline cli/registry/client/fetcher.go]: The name was a bit confusing, so checked if `reference.Domain()` returned the port-number as well, but looks like it does 😅 👍  https://github.com/docker/distribution/blob/6170ac53daed40ebbebc9fe5f482495d01f09f12/reference/reference_test.go#L51-L55

**Comment by thaJeztah** [comment]
ping @justincormack @silvin-lubecki ptal

File: cli/registry/client/fetcher.go (hunk 1 above)
Comment (clnperez) [reply cli/registry/client/fetcher.go]: yes it does. i double-checked that b/c i had the same concern. :) thanks @thaJeztah!

File: cli/registry/client/fetcher.go [hunk 2]
```diff
@@ -262,12 +262,18 @@ func (c *client) iterateEndpoints(ctx context.Context, namedRef reference.Named,
...
 // allEndpoints returns a list of endpoints ordered by priority (v2, https, v1).
-func allEndpoints(namedRef reference.Named) ([]registry.APIEndpoint, error) {
+func allEndpoints(namedRef reference.Named, insecure bool) ([]registry.APIEndpoint, error) {
 	repoInfo, err := registry.ParseRepositoryInfo(namedRef)
 	if err != nil {
 		return nil, err
 	}
-	registryService, err := registry.NewService(registry.ServiceOptions{})
+
+	serviceOpts := registry.ServiceOptions{}
```
Comment (silvin-lubecki) [inline cli/registry/client/fetcher.go]: nit: var serviceOpts registry.ServiceOptions

Comment (clnperez) [reply cli/registry/client/fetcher.go]: fixed that and re-pushed

**Comment by thaJeztah** [comment]
Thanks!
