### PR TITLE
disable pseudoterminal creation

### LINKED ISSUE #3019: Got an error with connecting daemon over ssh session
With setting ssh URL to the DOCKER_HOST environment var, the docker CLI does not work.

I'm using an EC2 instance (amazon linux 2) to run the docker daemon and set the ssh URL as the DOCKER_HOST. Then I ran the `docker containers` command on my local computer, but it had been failed with the error: `error during connect: Get http://docker/v1.40/containers/json: net/http: HTTP/1.x transport connection broken: malformed HTTP status code "pid"`

Next, I ran the command on the instance over the ssh connection; it seems to be succeeded.

How to fix it? or is this a bug?

```
$ docker -v
Docker version 19.03.13, build 4484c46d9d
```

I'm using docker for mac, Mac OS Mojave (10.14.6).

Best Regards.

### PR DESCRIPTION
**Pull request by trajano**
Fixes #3019

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

```markdown changelog


```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thank you for contributing! It appears your commit message is missing a DCO sign-off,
causing the DCO check to fail.

We require all commit messages to have a `Signed-off-by` line with your name
and e-mail (see ["Sign your work"](https://github.com/moby/moby/blob/v20.10.11/CONTRIBUTING.md#sign-your-work)
in the CONTRIBUTING.md in this repository), which looks something like:

```
Signed-off-by: YourFirsName YourLastName <yourname@example.org>
```

There is no need to open a new pull request, but to fix this (and make CI pass),
you need to _amend_ the commit(s) in this pull request, and "force push" the amended
commit.

Unfortunately, it's not possible to do so through GitHub's web UI, so this needs
to be done through the git commandline.

You can find some instructions in the output of the DCO check (which can be found
in the "checks" tab on this pull request), as well as in the [Moby contributing guide](https://github.com/moby/moby/blob/v20.10.11/docs/contributing/set-up-git.md).

Steps to do so "roughly" come down to:

1. Set your name and e-mail in git's configuration:

    ```bash
    git config --global user.name "YourFirstName YourLastName"
    git config --global user.email "yourname@example.org"
    ```

    (Make sure to use your _real_ name (**not your GitHub username/handle**) and e-mail)


2. Clone your fork locally
3. Check out the branch associated with this pull request
4. Sign-off and amend the existing commit(s)

    ```bash
    git commit --amend --no-edit --signoff
    ```

    If your pull request contains multiple commits, either squash the commits (if
    needed) or sign-off each individual commit.

5. _Force push_ your branch to GitHub (using the `--force` or [`--force-with-lease`](https://stackoverflow.com/questions/52823692/git-push-force-with-lease-vs-force) flags) to update the pull request.


Sorry for the hassle (I wish GitHub would make this a bit easier to do), and let me know if you need help or more detailed instructions!

File: cli/connhelper/connhelper.go [hunk 1]
```diff
@@ -79,3 +80,11 @@ func addSSHTimeout(sshFlags []string) []string {
 	}
 	return sshFlags
 }
+
+// Disable pseudo-terminal allocation.  This will prevent SSH from executing as a login shell
+func disablePseudoTerminalAllocation(sshFlags []string) []string {
+	if !strings.Contains(strings.Join(sshFlags, ""), "-T") {
```
Comment (tonistiigi) [inline cli/connhelper/connhelper.go:86]: I don't get the `strings.Join()`. All args should be separate already in `[]string` iiuc. `slices.Contains()` should be enough.

File: cli/connhelper/connhelper.go [hunk 2]
```diff
@@ -79,3 +80,11 @@ func addSSHTimeout(sshFlags []string) []string {
 	}
 	return sshFlags
 }
+
+// Disable pseudo-terminal allocation.  This will prevent SSH from executing as a login shell
```
Comment (tonistiigi) [inline cli/connhelper/connhelper.go:84]: function comments should start with a function name in Go per convention

**Review by tonistiigi — APPROVED** [review]
Content SGTM, but please rebase/squash to clean up the merge commits in the PR.

edit: and DCO as well

**Comment by trajano** [comment]
Ok I think I did the DCO now..  I added a test as well so I don't get 0% code cov

File: cli/connhelper/connhelper.go [hunk 3]
```diff
@@ -52,6 +52,7 @@ func getConnectionHelper(daemonURL string, sshFlags []string) (*ConnectionHelper
 					args = append(args, "--host", "unix://"+sp.Path)
 				}
 				sshFlags = addSSHTimeout(sshFlags)
+				sshFlags = disablePseudoTerminalAllocation(sshFlags)
```
[the remark this answers is not in the document]
Comment (trajano) [reply cli/connhelper/connhelper.go:55]: /shrug 
I don't think I'll do anything with this comment for now.

[the remark this answers is not in the document]
Comment (trajano) [reply cli/connhelper/connhelper.go:55]: TBH I was surprised that you call `ssh` rather than having a specific SSH go library.

**Review by thaJeztah — APPROVED** [review]
changes LGTM


I'll do a quick rebase/squash

File: cli/connhelper/connhelper.go [hunk 4]
```diff
@@ -79,3 +80,14 @@ func addSSHTimeout(sshFlags []string) []string {
...
+// disablePseudoTerminalAllocation disables pseudo-terminal allocation to
+// prevent SSH from executing as a login shell
+func disablePseudoTerminalAllocation(sshFlags []string) []string {
+	for _, flag := range sshFlags {
+		if flag == "-T" {
+			return sshFlags
+		}
+	}
+	return append(sshFlags, "-T")
+}
```
Comment (vvoland) [inline cli/connhelper/connhelper.go:93]: Shouldn't this also check if `-t` has been specified explicitly and don't apply the `-T` in this case?

Comment (laurazard) [reply cli/connhelper/connhelper.go:93]: Not sure about that – this PR disables pseudo-tty allocation for `ssh`. Using `-t` should continue working regardless, as that impacts allocating a pseudo-tty inside the container, but I don't think that somehow requires `ssh` to be a pseudo-tty as well.

Comment (laurazard) [reply cli/connhelper/connhelper.go:93]: I guess this should be easy to check – I'll take a look.

Comment (laurazard) [reply cli/connhelper/connhelper.go:93]: This works fine/as expected.

**Comment by laurazard** [comment]
Should we backport this one to 27.x? @vvoland @thaJeztah

File: cli/connhelper/connhelper.go (hunk 4 above)
Comment (thaJeztah) [reply cli/connhelper/connhelper.go:93]: Ah, yes, we should probably skip if that's the case.

Probably not immediately critical for us because we don't set other options, but other users of the module technically could. And it doesn't seem like it would hurt to add the check.

**Comment by thaJeztah** [comment]
I think back porting would be ok? I also had that minor follow up, which should be safe.

File: cli/connhelper/connhelper.go (hunk 4 above)
Comment (laurazard) [reply cli/connhelper/connhelper.go:93]: Ahhh 😅 for sure. I think that's okay, do we expect users to set flags in their context?

Comment (vvoland) [reply cli/connhelper/connhelper.go:93]: Ah right, you can't set that via context 😅 It's only with this `GetConnectionHelperWithSSHOpts` that isn't used on our side.

Comment (thaJeztah) [reply cli/connhelper/connhelper.go:93]: I don't think there's ways to customise these currently, unless there's some options inherited from the ssh-config. The ability to set options was added in https://github.com/docker/cli/pull/2541#discussion_r480098871 (some of the discussion / context related to it in that comment)
