### PR TITLE
Convert ports before parsing.

### LINKED ISSUE #1962: Port out of bounds gives error 'invalid publish opts format'
**Description**

When run with a port out of bounds throws wrong error saying about options format instead of say port does not exist, or something related.

**Steps to reproduce the issue:**
1. run `docker run -it -p 80801:80 --rm nginx:1.17.0-alpine /bin/sh`

**Describe the results you received:**
docker: invalid publish opts format (should be name=value but got '80801:80').
See 'docker run --help'.

**Describe the results you expected:**
docker: invalid port '80801:80'.

**Additional information you deem important (e.g. issue happens only occasionally):**
first time happens. 
if run `docker run -it -p 10801:80 --rm nginx:1.17.0-alpine /bin/sh`. works!

`invalid publish opts format (should be name=value but got '80801:80').` has nothing to do with the problem.

**Output of `docker version`:**

```
Client:
 Version:           18.09.6
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Tue May  7 17:57:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 24
 Running: 11
 Paused: 0
 Stopped: 13
Images: 382
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 641
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: error
 NodeID: 
 Error: manager stopped: failed to listen on remote API address: listen tcp 0.0.0.0:2377: bind: address already in use
 Is Manager: false
 Node Address: 192.168.15.10
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: 949e6fa (expected: fec3683)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-21-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.64GiB
Name: carlos-lenovo
ID: F2JD:NC3H:VAFO:CZVL:2XRJ:FY3Q:TQWW:SFJ2:CTFL:7V5T:EV3G:BDT6
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 110
 Goroutines: 119
 System Time: 2019-06-20T13:26:43.012530765-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by thaJeztah**
carry of https://github.com/docker/cli/pull/1965 (original branch was gone)

Refactor code to allow mixing notation with -p
Closes #1962 
closes https://github.com/docker/cli/pull/1965
closes https://github.com/docker/cli/pull/2041
closes https://github.com/docker/cli/pull/2151

Signed-off-by: Aleksander Piotrowski <apiotrowski312@gmail.com>

**- What I did**
After refactoring and bug fixing. Docker provides better error message with invalid port:
`docker run --rm -p 8080:87888888 busybox`

and works with mixed notation like:
`docker run --rm -p 8080:80 -p published=1500,target=444 busybox`

**- How I did it**
I changed parsePortOpts, before it was iterating over all `-p` args and assuming that all of them are in the same notation. My fix is to iterate over all args and change every with `=` to short notation and then parse it. 

**- How to verify it**
`docker run --rm -p 8080:80 -p published=1500,target=444 busybox`
`docker run --rm -p 8080:87888888 busybox`

**- Description for the changelog**
Fix a bug with parsing `-p` flag with mixed notation

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

File: cli/command/container/opts.go [hunk 1]
```diff
@@ -380,21 +380,18 @@ func parse(flags *pflag.FlagSet, copts *containerOptions, serverOS string) (*con
...
+		return nil, err
+	}
 
-		ports, portBindings, err = nat.ParsePortSpecs(publishOpts)
+	ports, portBindings, err = nat.ParsePortSpecs(convertedOpts)
 
-		if err != nil {
-			return nil, err
-		}
+	// If simple port parsing fails try to parse as long format
```
Comment (zappy-shu) [inline cli/command/container/opts.go]: This comment can be removed

File: cli/command/container/opts_test.go [hunk 2]
```diff
@@ -854,3 +854,34 @@ func TestParseSystemPaths(t *testing.T) {
...
+func TestConvertToStandardNotation(t *testing.T) {
+	valid := map[string][]string{
+		"10:10/tcp":               {"target=10,published=10"},
+		"30:30":                   {"30:30"},
+		"20:20 80:4444":           {"20:20", "80:4444"},
+		"2500:1500/tcp 1300:1300": {"target=2500,published=1500", "1300:1300"},
+		"200:1500/tcp 80:90/tcp":  {"published=1500,target=200", "target=80,published=90"},
+	}
+
+	inValid := [][]string{
```
Comment (zappy-shu) [inline cli/command/container/opts_test.go]: nit: doesn't need a capital `V`

**Comment by thaJeztah** [comment]
rebased, and addressed nits 👍 ptal

**Comment by thaJeztah** [comment]
ping @silvin-lubecki PTAL

File: cli/command/container/opts.go [hunk 3]
```diff
@@ -381,32 +381,28 @@ func parse(flags *pflag.FlagSet, copts *containerOptions, serverOS string) (*con
 	publishOpts := copts.publish.GetAll()
 	var ports map[nat.Port]struct{}
 	var portBindings map[nat.Port][]nat.PortBinding
+	var convertedOpts []string
```
Comment (silvin-lubecki) [inline cli/command/container/opts.go]: nit: use a `var` block ?

File: cli/command/container/opts.go [hunk 4]
```diff
@@ -796,19 +792,22 @@ func parseNetworkAttachmentOpt(ep opts.NetworkAttachmentOpts) (*networktypes.End
...
+			for _, param := range strings.Split(publish, ",") {
+				opt := strings.Split(param, "=")
+				if len(opt) < 2 {
+					return optsList, errors.Errorf("invalid publish opts format (should be name=value but got '%s')", param)
+				}
+				params[opt[0]] = opt[1]
 			}
-
-			params[opt[0]] = opt[1]
+			optsList = append(optsList, fmt.Sprintf("%s:%s/%s", params["target"], params["published"], params["protocol"]))
```
Comment (thaJeztah) [inline cli/command/container/opts.go]: Note; this needs to be updated once https://github.com/docker/cli/pull/2252 is merged


Also; looking at how it's serialised to a string: 

- host-ip is not in the serialised form. while this looks to be currently not supported in the long form (we should), having a combination of "long" and "short" options could possibly mean that duplicates go unnoticed (I'd have to check). i.e., `-p 0.0.0.0:8080:80` is the equivalent to `-p published=8080,target=80`, but the latter is serialised to `8080:80` (not `0.0.0.0:8080:80`). Then again, we may already have a problem if `-p 0.0.0.0:8080:80` and `-p 127.0.0.1:8080:80` are both set 🤔 
- the long-form `mode=host` is only supported for swarm services (wondering if it should be added as a no-op option for `docker run` 🤔 

Perhaps with some refactoring, we can re-use the `PortOpt` type for both `docker run` and `docker service` (separating validation to produce errors on options that are not supported by either `docker run` or `docker service`); https://github.com/docker/cli/blob/2634562119dd5b4e64d529d1aa5e16f760382d5f/opts/port.go#L29

File: cli/command/container/opts.go (hunk 3 above)
Comment (thaJeztah) [reply cli/command/container/opts.go]: Ah, yes, I'll update once the other PR is merged (and this one rebased)

**Comment by thaJeztah** [comment]
@silvin-lubecki updated; PTAL
